### ISSUE TITLE
Can I have A key?

### ISSUE THREAD

**Issue by Tyler3D** [AJS-development/OpenAgar#13]
My ID is
hxk7FlyGapMUvOvBaYKs

**Comment by Tyler3D** [comment]
@Andrews54757

**Comment by Andrews54757** [comment]
798360164236. But note it won't work now as I am updating the client

**Comment by Tyler3D** [comment]
@Andrews54757 Ok

**Comment by Tyler3D** [comment]
@Andrews54757 Can you give me mine for future use though?

**Comment by LegitSoulja** [comment]
@Andrews54757 I GOT THE SOURCE!. Check gitter asap.

**Comment by Tyler3D** [comment]
@Andrews54757

**Comment by LegitSoulja** [comment]
@Tyler3D what future use? The client or the key? Be specific.

**Comment by LegitSoulja** [comment]
If the client then no. It contains sensitive information which cannot be leaked, nor used by any other.

**Comment by Tyler3D** [comment]
@LegitSoulja No I want A key to try out OpenAgar

**Comment by Tyler3D** [comment]
And Im not a computer newbie

**Comment by Tyler3D** [comment]
Also why does the client have sensitive info?

**Comment by LegitSoulja** [comment]
@Tyler3D yes the key can always be used if you don't destroy the backup file inside openagar. 

If you do however, a new ID will be generated and you'll need a new key. So just be careful with updating. 

And the client is sensitive because there's now a client & server authentication. Used to make sure real players are connecting to the server, other than bots.

Mainly, for you to be able to connect to the server the client will authenticate you so that you can join the server. 

Therefor, there can only be 1 client, that will work with open agar. No other.

**Comment by LegitSoulja** [comment]
Here's your key btw

'''
798360164265
'''

**Comment by Tyler3D** [comment]
@LegitSoulja Thanks

**Comment by Tyler3D** [comment]
And ok

**Comment by Tyler3D** [comment]
@LegitSoulja 
The backup file is the controller.js?
It loads first so, thats my guess.

**Comment by Tyler3D** [comment]
I got
module.js:327
throw 327;
^

**Comment by Tyler3D** [comment]
@LegitSoulja 
Ok I fixed it. But, I need another key for my new ID. :/

**Comment by Tyler3D** [comment]
@LegitSoulja PHKJvFZgsyAYsYU7TH7g

**Comment by LegitSoulja** [comment]
No, the backup file is not controller.js. The backup file is the "backup" file.

**Comment by Tyler3D** [comment]
Oh I didn't notice it

**Comment by Tyler3D** [comment]
@LegitSoulja  Can you generate a new key for me

**Comment by Tyler3D** [comment]
PHKJvFZgsyAYsYU7TH7g

**Comment by Tyler3D** [comment]
I messed up with the keys and had to start over

**Comment by LegitSoulja** [comment]
@Tyler3D 

`128417946742`

**Comment by Tyler3D** [comment]
@LegitSoulja Ok Thanks

**Comment by Tyler3D** [comment]
Now when I join I get. Server could not be verified. It might have been a mock-server!

**Comment by Tyler3D** [comment]
Is the client being worked on?

**Comment by Tyler3D** [comment]
Still

**Comment by LegitSoulja** [comment]
@Tyler3D The client needs updating. I thought andrew already did, but I guess not. We have to wait I guess.

**Comment by Tyler3D** [comment]
Ok

**Comment by LegitSoulja** [comment]
@Tyler3D it has been updated. http://play.ogarul.io/new

**Comment by Tyler3D** [comment]
@LegitSoulja 
@Andrews54757 
Nice Job on the code. Its impressive. It's hard to imagine that even though you are limited by one core, you can still play with over 1500 bots!

**Comment by Andrews54757** [comment]
Actually, I made the limit 2 cores

**Comment by Tyler3D** [comment]
@Andrews54757 @LegitSoulja May I have another key? I didn't delete the backup yet, after I updated the console says "Invalid Key". My id is : 7A19ZN9ZRxoKWjJdhzE4

**Comment by Andrews54757** [comment]
@Tyler3D , why dont you just make your own by singing up at login.opnagar.us. I will make an exception so you can.

**Comment by LegitSoulja** [comment]
New site design/layout coming soon.
- Better UI.
- Core system re-wrote, more faster and efficient.
- More faster page loading times.
- Users, Chat, PM, and server list.
- Updates (Based off GitHub API(Commits))
- Guides (Setup, hosting, managing etc).
- Backend panel. (Doing last)

- [ ] Status: 30% (Hopefully finish before New Years)

##### Future plugins coming soon
- AudioAPI
- Server Controller (Control server via site)
- More coming soon. 

(Note: Some plugins won't be brought back from OgarUl).

@Andrews54757
I thought there was gonna be a web console in which you can control the server via web? We could implement it with the server owner @ login.

**Comment by Andrews54757** [comment]
@LegitSoulja , did you look at gitter?

**Comment by FantasyIsBae** [comment]
@LegitSoulja If you are gonna implement a web console take a look at [this](https://www.npmjs.com/package/web-terminal)

**Comment by LegitSoulja** [comment]
@FantasyIsBae I hate using third party. Like to make my own things. 

@Andrews54757 Um, no. Do I need to?

**Comment by Tyler3D** [comment]
@Andrews54757 Thanks. @LegitSoulja And nice!

**Comment by LegitSoulja** [comment]
@FantasyIsBae besides, that is crap and incompatible with OpenAgar use. OgarConsole is crap, but I've stepped up my game with nodejs.

**Comment by LegitSoulja** [comment]
Really advanced in all in general.

**Comment by LegitSoulja** [comment]
Well not advanced but more efficient

**Comment by LegitSoulja** [comment]
Techniques sure does pay off

**Comment by FantasyIsBae** [comment]
Yes I understand , you can personalise your own stuff , and add more stuff to it too , it was only a suggestion anyways lol @LegitSoulja
