### ISSUE TITLE
How do you get a key?

### ISSUE THREAD

**Issue by DaAwesomeRazor** [AJS-development/OpenAgar#14]
Who do I contact to get a key?
My Id is vdqHqEPEDr6ZwdWzH5DV

**Comment by Andrews54757** [comment]
115210652177

**Comment by Andrews54757** [comment]
Note that it won't work now since I am updating the client

**Comment by DaAwesomeRazor** [comment]
Ok, thanks for the key. I will check it out tommorow then

**Comment by LegitSoulja** [comment]
@DaAwesomeRazor it has been updated. http://play.ogarul.io/new
