### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by G047** [AJS-development/OpenAgar#16]
Agar.io's C++ servers are believed to run two threads: One for handling the protocol, and another for handling the quad tree (collisions). This method of doing it works well as when "someone" runs 400+ bots on there servers, There is no lag.

The nodejs cluster module makes it extremely easy and efficient to share data between "workers" although "worker to worker" data transfer is not possible, that shouldn't be a problem. Using the nodejs cluster you can share Arrays, Objects, and anything else between workers with almost 0 delay. This should stop the server slow down effect that happens with a large amount of bots.

**Comment by Andrews54757** [comment]
Maybe later, but know that sending data to another thread isn't so easy. But also know that bots run in  a separate process already. Im gonna do this in the future.

**Comment by Andrews54757** [comment]
Actually, I don't think this is worth it. Sockets are already super efficient and can handle maybe a thousand players. I redesigned it top to bottom. The reason is because:

1. Of the SmartNodes protocol I made
2. The slow FPS protocol.

**Comment by Andrews54757** [comment]
So basically, this means that data is sent smartly. Unlike other protocols, most data is sent only once, (food for example). Because the client is made to "remember" the nodes. So when I send a food cell once, there is no need to send it again. Or ejected mass, I only send the data once, but the coordinates are send multiple times because it is moving. Also, the slow FPS protocol, makes the fps 10 frames,  from 50 frames. This works because the client knows where its gonna go so the paths are predetermined.

**Comment by ZfsrGhS953** [comment]
On ArcadeGo streams, which I believe had 1k players in a single server, the server ran at about 4 fps. Petridish Ogar runs 1.5k bots (that update every tick) on i7-4790 stock at about 12 fps. On most xeon processors used by agar.io servers, assuming they run at 2.66GHz, 1k bots would run at 12 fps, or 3 times faster than vanilla agar.io servers (assuming bot AI CPU usage is same as websocket connection CPU usage). @Andrews54757 said that OpenAgar runs 2 times faster than MultiOgar. That means with 1k players OpenAgar servers are going to run at 24fps, or near full speed!

**Comment by Andrews54757** [comment]
I meant 2 times efficient, not faster.

**Comment by Andrews54757** [comment]
What do you mean above?

**Comment by ZfsrGhS953** [comment]
I wanted to say that vanilla server runs 3 times slower than Petridish Ogar.

**Comment by Andrews54757** [comment]
?

**Comment by ZfsrGhS953** [comment]
This is Petridish Ogar: https://github.com/ZfsrGhS953/Petridish-Ogar/ And this is vanilla server played with around 1k players: https://www.youtube.com/watch?v=bjzAsAI1ujQ

**Comment by ZfsrGhS953** [comment]
@G047 400 bots without lag? (I know this is 700 bots, but you get the point) https://www.youtube.com/watch?v=3TM4PbRLHg8 The server runs below half speed.

**Comment by Andrews54757** [comment]
I don't think nodes are sent at 12 fps

**Comment by ZfsrGhS953** [comment]
They are, but the client interpolates the updates

**Comment by Andrews54757** [comment]
Well in the main loop code, updating clients happen at every tick

**Comment by Andrews54757** [comment]
And vanilla agar.io is made to have 50 fps. it says so on the client

**Comment by Andrews54757** [comment]
Or am I wrong. I don't know. its the morning

**Comment by ZfsrGhS953** [comment]
In that case, Petridish Ogar is 1.5x faster than vanilla server. Still quite good because agar is written in C++ and Petridish Ogar is written in node.js

**Comment by Andrews54757** [comment]
Well look at this: http://astr.io. It says the fps is about 50. Like I said. But also like I said, I slowed the fps to 10 fps for OpenAgar

**Comment by ZfsrGhS953** [comment]
That's client-side FPS. I'm talking about the server.

**Comment by Andrews54757** [comment]
Try making your server run at 10 fps actually, and the client will look like agar.io when it was laggy

**Comment by Andrews54757** [comment]
The normal fps for servers is 50

**Comment by ZfsrGhS953** [comment]
I tried it already (at 12.5 fps) and it was quite playable, aside from slightly glitchy cell collisions. I think that's why you asked Barbosik [here](https://github.com/Barbosik/MultiOgar/issues/410) to help you with OpenAgar collisions.

**Comment by Andrews54757** [comment]
I am doing a face palm now.

**Comment by Andrews54757** [comment]
I MEANT THAT THE SERVER RUNS VERY FAST, BUT DATA IS SEND TO THE CLIENT AT 10 FSP!!! SO COLLISIONS ARE NORMAL!!!

**Comment by Andrews54757** [comment]
And I asked Barbosik to make it efficient, the collision code. Not what you said

**Comment by Andrews54757** [comment]
It is also impossible for your "petridish ogar" to run at 12 fps. It would make the game laggy unless you used the slow fps protocol

**Comment by Andrews54757** [comment]
Take a look at this: https://github.com/AJS-development/OpenAgar/blob/master/source/core/socketService.js#L75

**Comment by ZfsrGhS953** [comment]
"Quite playable" doesn't mean "not laggy"

**Comment by Andrews54757** [comment]
YES, but I am saying that OpenAgar's updates are 10 fps but LAG IS NOT VISIBLE!

**Comment by Andrews54757** [comment]
It is perfectly smooth

**Comment by Andrews54757** [comment]
OpenAgar's client can predict cell movement. thats why

**Comment by Andrews54757** [comment]
I put in just the same amount of work into the client as I did to the server

**Comment by Andrews54757** [comment]
And no, I am not going into specific details about the slow fps protocal. Because It is my hard work

**Comment by LegitSoulja** [comment]
C doesn't support io which openagar is using socket.io.

I was going to make the server (OgarUnlimited) in C, but I changed my mind after I seen the results of this.

Since C doesn't support io, and openagar is websocket this issue is closing.

**Comment by nuclearc** [comment]
@ZfsrGhS953 did you tested new agario servers with 1000 players? i just tested it and there was no lag.

**Comment by Andrews54757** [comment]
?

**Comment by nuclearc** [comment]
@ZfsrGhS953 said that agario servers are running slower than his Petridish-Ogar, so i just run 400 bots on agario server with more than 500 players and there were no lag. If he want i can run that sae 400 bots on his petridish ogar and see what happens.

**Comment by G047** [comment]
I think you misunderstood what point I was trying to get across. MultiOgar is currently the fastest agar.io protocol private server that I know of, but when too many players/bots are ingame the server grinds to a halt. This is because of these couple lines of code, `
    // update
    for (var i = 0; i < this.clients.length; i++) {
        this.clients[i].playerTracker.updateTick();
    }
    for (var i = 0; i < this.clients.length; i++) {
        this.clients[i].playerTracker.sendUpdate();
    }`

Because the server has to loop through around 1000 players it takes a while to loop, if multiple "workers" split this task between them it would be a large improvement with the server speed. You don't even need to share that much data with the workers only the current playerTracker and it can do the rest.

**Comment by Andrews54757** [comment]
@G047 That is very impractical

**Comment by Andrews54757** [comment]
But OpenAgar, detects lag, and if there are too many players, the game doesn't halt, but slows down

**Comment by G047** [comment]
@Andrews54757 More impractical than running two for loops that go through each player?

**Comment by Andrews54757** [comment]
@G047 I hope you realize that running different process are harder than you think

**Comment by G047** [comment]
@Andrews54757 My nodejs agar bots run multiple processes, they work quite well

**Comment by Andrews54757** [comment]
Because there is no such thing as shared data in nodejs

**Comment by Andrews54757** [comment]
Your agar bots, don't need to send data to each other often. But an agar.io server does

**Comment by Andrews54757** [comment]
Look at childService.js and child/manager.js

**Comment by Andrews54757** [comment]
Open agar already uses two processes. One for all the physics and player sockets, and the second for all the bots and leaderboard and other minor cpu consuming tasks

**Comment by G047** [comment]
Why only one worker working on physics?

**Comment by Andrews54757** [comment]
Making bots run at a different cpu made OpenAgar less efficient. Since every node that that is updated on one process needs to be sent to the other so the bots can "see" them. But it would be worth it when bots become truly intelligent, consuming lots of cpu, so thats when it will shine, since if I didn't make it on a child process, the efficiency would be O(n) with n being the complexity of the bots, but if I did, it would be O(1)

**Comment by Andrews54757** [comment]
If you plot the efficiency, you will see that if I didn't run bots in a separate process, as the bots's complexity increases, the amount of lag also increases linearly, but when I do, it remains constant

**Comment by Andrews54757** [comment]
But currently, since the bots are not inteligent, all they do is go to a random pos, it would be more efficient to not run it in a process

**Comment by Andrews54757** [comment]
And if there were more workers working on physics, the quality of it will drop significantly, remember, sending data to another process is not instant.

**Comment by G047** [comment]
Yea but using workers for bots isn't what I'm on about, Did you find a workaround for 
`for (var i = 0; i < this.clients.length; i++) {`

**Comment by Andrews54757** [comment]
Why do I need to?

**Comment by G047** [comment]
As the number clients grow so does the time it takes to run the for loop

**Comment by Andrews54757** [comment]
I also hope you understand the really stupid yet important event loop

**Comment by Andrews54757** [comment]
@G047 So what can we do about it?

**Comment by Andrews54757** [comment]
Nothing

**Comment by G047** [comment]
Yea, but its a large drawback

**Comment by Andrews54757** [comment]
So, not if you make the code that runs inside the for loop efficient

**Comment by Andrews54757** [comment]
for loops are actually incredibly fast

**Comment by Andrews54757** [comment]
But the code that runs inside is not

**Comment by G047** [comment]
ill run some benchmarks

**Comment by Andrews54757** [comment]
I made sure OpenAgar's loops are pretty efficient though

**Comment by G047** [comment]
What side-effects would this have?
`    for (var i = 0; i < this.clients.length; i++) {
        this.clients[i].playerTracker.updateTick();
    }
    for (var i = 0; i < this.clients.length; i++) {
        this.clients[i].playerTracker.sendUpdate();
    }
};`

into 

`for (var i = 0; i < this.clients.length; i++) {
        this.clients[i].playerTracker.updateTick();
        this.clients[i].playerTracker.sendUpdate();
    }
};`

**Comment by Andrews54757** [comment]
It would make the game laggier

**Comment by Andrews54757** [comment]
I am not going to explain, just read about the event loop
