### ISSUE TITLE
Key request

### ISSUE THREAD

**Issue by Niall7459** [AJS-development/OpenAgar#22]
Hey there, It would be nice to test out this new software and possibly use it on myold agar servers.

My id is: BsTFsj3P2gRmnqBoKOQP

**Comment by Niall7459** [comment]
Is this protocol 5 server emulator?

**Comment by Niall7459** [comment]
Does it include client?

**Comment by Niall7459** [comment]
@Andrews54757

**Comment by Andrews54757** [comment]
167370711067

**Comment by Andrews54757** [comment]
Client is at play.ogarul.io/new
