### ISSUE TITLE
Key Request

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/OpenAgar#25]
Don't waste issues over key requests. Just request them below.

- Provide your I.D prior to the startup of OpenAgar. 

We will soon provide your key within 24 hours. A site will be coming soon to manage your servers and keys. That's when Andrew allows me too. Therefor, waiting before development.

**Comment by l3mpik** [comment]
Key: m9qcKd2DckdT4tQXsoQJ

**Comment by LegitSoulja** [comment]
@l3mpik
`111985101065`

**Comment by l3mpik** [comment]
@LegitSoulja  Thanks :)

**Comment by G047** [comment]
YmQCZirzmFNUP6k1FQ0O

**Comment by PsycoYT** [comment]
iVQUNf6KRtpqn3Kyu9v1

**Comment by LegitSoulja** [comment]
@G047
`122572720515`

**Comment by LegitSoulja** [comment]
@PsycoYT
`731985970536`

**Comment by agariotips** [comment]
jls6oCXGAwK997cWpz09

**Comment by Andrews54757** [comment]
707639334484

**Comment by ImHyper** [comment]
@LegitSoulja  @Andrews54757 Where do I find the key in my files??

**Comment by Andrews54757** [comment]
Quoting LegitSoulja,
> When the bell rings

**Comment by ImHyper** [comment]
@Andrews54757 Huh??

**Comment by Andrews54757** [comment]
When it becomes clear to you. We will not explain how to use for computer newbies. Search up on google. The readme should be enough

**Comment by ImHyper** [comment]
@Andrews54757 The problem is that the README talks about files I don't have.

**Comment by Andrews54757** [comment]
@ImHyper It is not hard. If you had computer knowledge, then you will definatly figure it out. There are no files that are not included thats in the readme. Follow the instructions exactly

**Comment by LegitSoulja** [comment]
@ImHyper maybe you should stay off the sugar/caffeine.

There's nothing in the readme about files you need. Everything comes as it is. Some things are not shown due to you not following the readme,

**Comment by Ckicky** [comment]
N6OdSyvkRfdUeuHRgToX

**Comment by PrinceDark9243** [comment]
XkXhZZv5MmoILGNhFpJ9

**Comment by LegitSoulja** [comment]
@Clicky @PrinceDark9243  Keys are no longer being given out. 

Locking this issue.
