### ISSUE TITLE
Error : kicked: Timeout: Your client waited too long

### ISSUE THREAD

**Issue by PsycoYT** [AJS-development/OpenAgar#26]
why?

**Comment by LegitSoulja** [comment]
Looks like you connected before you started the server. Start the server first then connect to the client. Thanks

**Comment by PsycoYT** [comment]
same error...

**Comment by Andrews54757** [comment]
Solution: Your browser is bad.

**Comment by PsycoYT** [comment]
LOL @Andrews54757  google chrome is bad ?

**Comment by Andrews54757** [comment]
Or your computer or network. That message only happens when your client takes too long to respond to the server

**Comment by Andrews54757** [comment]
Its to prevent lag

**Comment by LegitSoulja** [comment]
If it's localhost maybe you should get off wifi
