### ISSUE TITLE
What Happened?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/OpenAgar#29]
I See you have created ThreeLetters, and i have been removed from ajs
why is this?

**Comment by Andrews54757** [comment]
I dont think I removed you. @LegitSoulja did

**Comment by LegitSoulja** [comment]
@SharkFinPro

I think you should wait a little while before joining. I didn't technically remove you, but you was placed under as an outside contributor.

**Comment by LegitSoulja** [comment]
@Andrews54757 so can we do this http://forum.ogarul.io/threads/openagar-soon-termination.117/live ??

Or what are the future plans now? I need to know

**Comment by Andrews54757** [comment]
So heres the plan: OpenAgar is not going to be abandoned. It will not be priority. But currently, I am thinking of creating https://github.com/ThreeLetters/CodersAssemble, similar to c9.io, google docs, and git all combined togethor. Also I cannot decide whether the server should be in nodejs or just php. But then, I want to have a terminal, like c9.io, and that is probably only achieved through nodejs

**Comment by LegitSoulja** [comment]
So I'm guessing you don't need me anymore

**Comment by LegitSoulja** [comment]
@Andrews54757 btw, together.js would be helpful in that case.

**Comment by Andrews54757** [comment]
No, I invited you to the new one

**Comment by Fantasy-Agario** [comment]
@Andrews54757 One question ,

Why did you decide to stop Game Development ?

**Comment by LegitSoulja** [comment]
@Fantasy-Agario because kids are making good things bad. Andrew finally realized how people are.

If OpenAgar don't be semi private it'll turn into how ogarul was.

**Comment by Fantasy-Agario** [comment]
Yeah i agree @LegitSoulja ,

Unfortunately, it tends to be the good or free things that get ruined 
And making OpenAgar semi-private is a good way to solve that :) 
-----------------------------------------------------------------------
Are the forums gonna open again anyways?

**Comment by LegitSoulja** [comment]
@Fantasy-Agario I really want to carry out my ideas/thoughts I had but I guess andrew doesn't like it.

And idk will the forums open back up again. There's no use for it anymore. I really don't know what to do right now. I'm still kindof confused.

**Comment by Fantasy-Agario** [comment]
Well take the time to think before you make your next move :) @LegitSoulja 

And yeah, i guess there isn't any use for the forums anymore .
Do u know what Andrew is going to move on and do ?

**Comment by LegitSoulja** [comment]
@Fantasy-Agario I really don't have no idea. 

And next move? There might not be another.

**Comment by Fantasy-Agario** [comment]
Seems like npm package stuff to me 

And I don't mean like Developer wise as it can be anything 
Music , etc :)

**Comment by LegitSoulja** [comment]
Anyways, im planning a Christmas vacation for my birthday that's coming up. I will be gone for about a few weeks. I'll be spending some days in Dubai.

**Comment by Fantasy-Agario** [comment]
Yeah enjoy that it will do u good :P

**Comment by LegitSoulja** [comment]
@Fantasy-Agario Idk, Im planning on going back to work fully time, as being an engineer manufacturing vehicles on an assembly line.

I might quit being a dev. I wouldn't even have time to do anything.

**Comment by Fantasy-Agario** [comment]
I mean its your life , do what you think is best :)

**Comment by Fantasy-Agario** [comment]
I can't advise you cos i don't know you in person + im only 13 so yeah :D

**Comment by LegitSoulja** [comment]
@Fantasy-Agario Trust me, I know what's best for me. I've just been resting from school, and college lately. I guess it's time for me to get off my butt and work.

**Comment by Fantasy-Agario** [comment]
Yeah i guess so , what did u do in college anyways ?

**Comment by LegitSoulja** [comment]
I was a law student for a few months until I decided that I wasn't going to do anything with law. I wanted to be a lawyer, but I had other things in mind.

The courses I took was engineering, Accounting, Banking and Finance. I was going to do carpeting but decided that I enjoy electronics the most and did electrical tech instead, and also I took a business class. Because one day hopefully I'll be able to run my own business

I only did 2 years, I want to do more, but I don't need to, but I can to become better.

**Comment by Fantasy-Agario** [comment]
What sort of business do u want to run ?

**Comment by Fantasy-Agario** [comment]
Oh yeah Happy Birthday just in case i don't get a chance to tell you :D

**Comment by LegitSoulja** [comment]
@Fantasy-Agario 

I started a business a year ago with some friends. We are pretty much a free lancer group.

**Comment by LegitSoulja** [comment]
Plus, I will need alot of money to be able to start a legit business. But, that will be something I'll plan to invest for in the future.

**Comment by LegitSoulja** [comment]
I'll wait 5 more years when im 30. Maybe i'll get tired of working and decide to be a boss.

**Comment by Fantasy-Agario** [comment]
Ok , anyway Happy Birthday just in case i don't get to tell u :)

**Comment by Fantasy-Agario** [comment]
"Legit" Business XD

**Comment by Fantasy-Agario** [comment]
Yeah i can't imagine what it would be like to be a business owner (Too much to get my head around)

**Comment by LegitSoulja** [comment]
@Fantasy-Agario it's funny how my name was "found"

**Comment by LegitSoulja** [comment]
During the times of my high school years I was into ROTC. That's where "Soulja" come from, and people used to call me legit cause everything I did or said was true.

**Comment by Fantasy-Agario** [comment]
Wow , short story that tells a lot .

**Comment by LegitSoulja** [comment]
There's more too it. Soulja isn't as a soldier. It's even a longer story lol

**Comment by Fantasy-Agario** [comment]
Can i hear it XD

**Comment by LegitSoulja** [comment]
http://www.urbandictionary.com/define.php?term=soulja

**Comment by LegitSoulja** [comment]
@Fantasy-Agario not that it was wrote in 2006

**Comment by Andrews54757** [comment]
@LegitSoulja You can open the forums and carry out whatever you want. And Happy Birthday! Also, I am planning to become a businessman, a ceo or something. It is my skill to lead people and get things done efficiently. But I need to get a MBA first.

**Comment by LegitSoulja** [comment]
@Andrews54757 Since you're gone, doing other things with no look out over the forums, I have to close the it down until I get back from Dubai

**Comment by LegitSoulja** [comment]
That'll be about a 2-3 week span

**Comment by LegitSoulja** [comment]
@Andrews54757 btw is your email the same as your PayPal?

**Comment by LegitSoulja** [comment]
@Andrews54757 Now we have a problem https://github.com/BHax-Development/OpenAgar/

**Comment by LegitSoulja** [comment]
We need to move away from github because github is pretty much open sourced, and public for whoever to use, obtain..

But you added a license. Which he will have to follow, but he is decrypting some files of yours.

Time to remove the client I guess.

**Comment by Andrews54757** [comment]
@LegitSoulja Dont worry about it. I thought of every thing people can do to hack.

**Comment by LegitSoulja** [comment]
@Andrews54757 The files are encrypted though. He is really close from decrypting everything.

**Comment by Andrews54757** [comment]
@LegitSoulja I will show you a secret. Go to gitter
