### ISSUE TITLE
Generate Your Own Key!

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/OpenAgar#31]
**T**here will be a new site in regards to people being able to generate there own key.

**A**s of now, a limit of 15 people will be able to register and be able to generate a key. In 2017 the user registration cap will be set to 30, allowing 30 people be able to generate a key, and so forward...

**Y**ou will only be allowed to have 1 valid key. More future predictions will allow you to have more keys.

**W**hen you generate your key, you are allowed to activate, and deactivate them. When you deactivate a key it cannot no longer be used, and you will need to activate it back to use it again. When you deactivate your key you could just be in risk of having your UID stolen, (given to another account).

**T**herefor, Only deactivate if you loose your key, or either want to give the ownership of it to someone else to manage.

###### Visit the generate keys page, and generate your key with a simple button!.

![captured](https://cloud.githubusercontent.com/assets/4976824/21596652/bd0e5ccc-d10b-11e6-8eb6-9d5787aafa2f.PNG)

###### Keep track of your active, inactive keys

![captured](https://cloud.githubusercontent.com/assets/4976824/21596701/bc0813ee-d10c-11e6-9889-d14b688ec524.PNG)

**Tutorial video** 
https://youtu.be/DuWfWbemIQw

**Register now before it's too late!**
http://login.opnagar.us/

**Comment by raphyjb** [comment]
Could you send me a key?

**Comment by Fantasy-Agario** [comment]
Quoting @LegitSoulja : 
> Keys are no longer being given out.

**Comment by LegitSoulja** [comment]
@raphyjb when I finish the site...

I've been kindof busy,

**Comment by LegitSoulja** [comment]
@Andrews54757 1 question.

What is the min-max length of a normal UID?.

**Comment by LegitSoulja** [comment]
@raphyjb @Fantasy-Agario Generate your key here http://opnagar.us/

**Comment by LegitSoulja** [comment]
Make sure if you ever update OpenAgar don't delete any files. Just overwrite them.

**Comment by LegitSoulja** [comment]
Because you won't be able to generate another key. There will be a solution to where you can delete your key but I haven't implemented it yet.

**Comment by Andrews54757** [comment]
@LegitSoulja The key algorithm is different now, I will update later

**Comment by LegitSoulja** [comment]
@Andrews54757 Ok, we need to implement this into OpenAgar, I can provide it however.

But the keys that are deleted after being generated need to be deactivated. Because I don't want people to delete them, then generate another key, and keep doing it.

**Comment by Andrews54757** [comment]
@LegitSoulja Check gitter

**Comment by LegitSoulja** [comment]
I changed the registered cap to 10. Only 10 people are allowed to be able to register, and get a key without any problems.

Cap will be increased in the future so go and register ASAP!.

**Comment by PrinceDark9243** [comment]
i registered how i can get the key

**Comment by Andrews54757** [comment]
@LegitSoulja I finished the key deactivation system

**Comment by Andrews54757** [comment]
Tested it and it works

**Comment by Andrews54757** [comment]
@LegitSoulja However, it would be nice to have a list of your deactivated keys as well, so you can reactivate them with a single button.

**Comment by Andrews54757** [comment]
And there is an issue, where you cannot reactivate deactivated keys

**Comment by Andrews54757** [comment]
@LegitSoulja The key generation max limit is not working for me. I made about 12 keys and it still worked. Or did you make it so I have unlimited keys? Anyway, another issue is that if you have multiple keys, you are only able to delete the first one on the list. And non valid bids, are accepted as well. We should check if the uid is exactly 20 characters long.

**Comment by Andrews54757** [comment]
@LegitSoulja And, in order to maximize storage, a system should be in place, so if a key is deactivated for x days, it will be deleted from the database

**Comment by Andrews54757** [comment]
@LegitSoulja I purged the database of invalid keys.

**Comment by LegitSoulja** [comment]
@Andrews54757 If they delete there key they can't get it back no activate it again. Once it's deleted it's no longer active.

Delete keys with caution.

And yes, you specifically can generate as many keys you want.

The delete button doesn't work for the other keys which I'll fix eventually.

And I asked you what was the min-max length of an ID but you didn't tell me anything

**Comment by LegitSoulja** [comment]
I'll list the deactivated keys, but it's pointless to allow people to activate them back. In that case, if they loose there ID and need another key they won't be able to do that since they already have A key in there account.

And removing keys from the database is a nono. People will generate and wait until they key is removed, and don't worry about the database size. There won't be no problems

**Comment by Fantasy-Agario** [comment]
Do u use Mysql to store the keys ? @LegitSoulja @Andrews54757

**Comment by LegitSoulja** [comment]
@Fantasy-Agario for security yes

**Comment by LegitSoulja** [comment]
I'm looking for someone to design the site for me. I hate CSS

**Comment by Fantasy-Agario** [comment]
Ok :) 

You don't want some kid looking through your keys n stuff anyways XD

**Comment by LegitSoulja** [comment]
@Fantasy-Agario it won't be possible.

**Comment by LegitSoulja** [comment]
Even if someone steals a key they won't be able to use it.

**Comment by LegitSoulja** [comment]
But there's public and private files

**Comment by Fantasy-Agario** [comment]
Yeh i know cos there's the machine ID's

**Comment by Andrews54757** [comment]
@LegitSoulja What is wrong with key reactivation and purge? If key reactivation is set up, so reactivation is not possible if the account reached the max (they would have to deactivate another key to free "keys"), then we have no problem for that. And key purging, I don't know what is wrong with that.

**Comment by LegitSoulja** [comment]
Yup, which cannot be modified

**Comment by LegitSoulja** [comment]
@Andrews54757 I just don't think it's a good idea to allow key reactivations.

And why purge? Or why even create a key validated on the client?

If someone create a key, and delete it'll they'll just wait until it's removed from the database to be able to use it. So speaking, they'll have limited keys.

**Comment by Fantasy-Agario** [comment]
@Andrews54757 Maybe set up a cooldown time for the key reactivation

**Comment by LegitSoulja** [comment]
/\ it's pointless.

**Comment by Andrews54757** [comment]
So this is what I am saying:


1. There would be a list of your keys. Activated keys and deactivated keys.
2. You can create a key as long as you don't exceed the limit
3. You can disable a key, so you can create another
4. When you want to use the key you just disabled, you disable one of the keys you have, in order to free space, so you can reactivate.

**Comment by LegitSoulja** [comment]
@Andrews54757 the point of deleting keys are for those people who failed to update correctly and loose there ID. 

Everyone who register will only be allowed to register 1 key, until it's deleted.

**Comment by Fantasy-Agario** [comment]
@LegitSoulja Ok ,its pointless :D

**Comment by Andrews54757** [comment]
Code wise:


```
// maxKeys = the max amount of keys
// keys = the amount of keys you have


function deactivate(key) {
keys --;
// do stuff
}
function activate(key) {
if (keys >= maxKeys) {
notify("You have exceeded the amount of keys.")
return;
}
// do stuff

}
function createKey() {
if (keys >= maxKeys) {
notify("You have exceeded the amount of keys.")
return;
}

// do something
}
```

**Comment by LegitSoulja** [comment]
-_-

**Comment by LegitSoulja** [comment]
If that's what you really want I'll do it when I have time

**Comment by Andrews54757** [comment]
@LegitSoulja It is because if you delete a key, it doesn't mean your id is reset, so that machine will forever be unable to run the program

**Comment by LegitSoulja** [comment]
@Andrews54757 Did you not read the reason why I even added key deletion?

**Comment by Andrews54757** [comment]
And, if you have a machine, and you have a key for that, but you are using someone else's computer temporarily, and you want to run the program, you could temporarily deactivate your home version, and activate the current computer's version, and when you get on your own again, you can deactivate the key you created in order to use your own again.

**Comment by Andrews54757** [comment]
@LegitSoulja No, I didn't read. But I am pretty sure it is to recover keys when a person loses it.

**Comment by LegitSoulja** [comment]
I said it twice

**Comment by LegitSoulja** [comment]
But yea I'll do whatever

**Comment by LegitSoulja** [comment]
BTW is anyone having problems logging in? I have one complaining he can't.

**Comment by Andrews54757** [comment]
no.

**Comment by LegitSoulja** [comment]
I fixed it. Those people that didn't have a bio couldn't login. I made a check for all data that is used on site. and bio is one of those that is less priority.

**Comment by LegitSoulja** [comment]
@Andrews54757 Another bug report

- Crashed after "Core Dump"

Node version: v7.2.0
OS: Linux 4.4 kernel and Manjaro KDE 16.01 64 bit

Reported by @makmm

**Comment by Andrews54757** [comment]
Obviously, the core dump shouldn't be used except for developers

**Comment by Andrews54757** [comment]
@LegitSoulja Did you finish the key deactivation/reactivation system?

**Comment by LegitSoulja** [comment]
@Andrew54757 I'm kindof busy right now,

But I fixed some things on the site as to the delete keys

**Comment by LegitSoulja** [comment]
I'll implement it sometime today

**Comment by LegitSoulja** [comment]
I need to think about how the content will be laid out before I throw it in

**Comment by LegitSoulja** [comment]
I might start redesigning everything before I add it

**Comment by LegitSoulja** [comment]
I hate CSS

**Comment by Fantasy-Agario** [comment]
@LegitSoulja I hate it too , so your not alone :)

**Comment by LegitSoulja** [comment]
@Andrews54757 is the client outdated?

**Comment by LegitSoulja** [comment]
@Fantasy-Agario I'm going to photoshop a template lol

**Comment by Fantasy-Agario** [comment]
@LegitSoulja lol

**Comment by LegitSoulja** [comment]
@Andrews54757 The system has been put into place. You're welcome.

**Comment by LegitSoulja** [comment]
But I don't know about deleting keys after days of being dis-activated. People will use it to register more keys, and wait until its removed to use it.

**Comment by Andrews54757** [comment]
@LegitSoulja The system doesn't work like that. If the immediate response from the server isn't 2, then it won't run. So it doesn't matter if it is in the database or not. The only thing it changes (being -1, 0, 1) is the message on quit, to notify the user what happened.

**Comment by Andrews54757** [comment]
@LegitSoulja The key generation button also doesn't work

**Comment by LegitSoulja** [comment]
@Andrews54757 Ah, I moved the script to the head, and it broke it.

Fixed..

**Comment by LegitSoulja** [comment]
Forcing page update

**Comment by Andrews54757** [comment]
Great. And did you make sure, that if I disable a key, and go on another account, and enable that key, there is no collision/error? It should be so that they can activate it, with the previous holder losing it.

**Comment by LegitSoulja** [comment]
@Andrews54757 You can't generate a key for a UID if that UID already exist

**Comment by LegitSoulja** [comment]
@Andrews54757 There will be a admin panel in the future in which we can moderate other accounts and do whatever with keys

**Comment by LegitSoulja** [comment]
That's another thing. I need to listen for new github accounts, and make sure people can't register 2 github accounts with the same ip address.

**Comment by Andrews54757** [comment]
Yes, but it would be nice, if this could work:

You have a OpenAgar server and its keys, on a computer, but you go to another computer and use it (disabling the first one and creating the second), then, when you go back to the first computer, you disable the new key, and enable the old key. Then, another person comes to the second computer, and uses his account to create/activate the key. Then the key will not be labeled as mine anymore. (it would be gone from the "your keys" list)

**Comment by Andrews54757** [comment]
@LegitSoulja It actually doesn't matter whether we check for IP addresses though, because smart people will use proxys

**Comment by Andrews54757** [comment]
Or we could set up our own user system

**Comment by LegitSoulja** [comment]
@Andrews54757 I could integrate the forums auth

**Comment by Andrews54757** [comment]
Anyway, do you understand what I mean above?

**Comment by LegitSoulja** [comment]
@Andrews54757 No, sorry. I'm trying my best to understand

**Comment by Andrews54757** [comment]
So basically, it means that disabled keys are not stuck with their accounts. Another user can "take" the disabled key of a user, in order to allow it so that if I deactivate a key on a machine, another user can activate it again, as his account, provided that he has the uid. Because in the current system, if you deactivate a key on a machine, that machine will be unusable until you activate it, even if you were only using that machine temporarily.

**Comment by LegitSoulja** [comment]
Ok I understand now.

**Comment by Andrews54757** [comment]
I can essentially set the system up. But I don't have encrypted files

**Comment by LegitSoulja** [comment]
@Andrews54757 it's simple actually.

I'll explain the framework of the site whenever you have time.

**Comment by Andrews54757** [comment]
CODE:

```
function createKey(uid) {
if (var a = queryUid(uid)) { // key was registered before
if (a.active == 0) { // activate as the account, and remove from old one

} else { // display error saying that it is already activated

}
} else { // create key like before

}
}

```

**Comment by LegitSoulja** [comment]
But on key creation I just need to check if the UID exist, and if it's not active in which another person can claim it, auto activate, and auto change the owner

**Comment by Andrews54757** [comment]
Yep, that is what I just put above

**Comment by LegitSoulja** [comment]
@Andrews54757 all the main functions are inside library/config.php

And the curl/ajax calls are in the core folder

**Comment by Andrews54757** [comment]
ok. Did you do it though?

**Comment by LegitSoulja** [comment]
Also the public folder contains keygen.js, there's a backup of the unencrypted

**Comment by LegitSoulja** [comment]
I'm going too

**Comment by Andrews54757** [comment]
Great! And sorry for pestering, It is my personality to check for any conditions.

**Comment by LegitSoulja** [comment]
@Andrews54757 I think im done. Needs to be tested tho.

**Comment by LegitSoulja** [comment]
@Andrews54757 I deactivated my key > FJo3ye4l5HqvCuIIe2u0

Try to steal it

**Comment by Andrews54757** [comment]
Key generation button doesn't work again

**Comment by LegitSoulja** [comment]
@Andrews54757 It does, but you have to wait a second before

**Comment by Andrews54757** [comment]
And did you check that before "stealing" a key from another, the person who stole it, has enough "space"?

**Comment by Andrews54757** [comment]
And did you also check that you cant steal your own keys?

**Comment by Andrews54757** [comment]
And I don't know why it is so slow to generate.

**Comment by LegitSoulja** [comment]
@Andrews54757 I know why it's slow, because I didn't give an error.

And, a user can't generate a key if they don't have no more key limits

and no you can't steal your own keys.

**Comment by Andrews54757** [comment]
ok, but I cant seem to steal your key

**Comment by Andrews54757** [comment]
try mine

**Comment by LegitSoulja** [comment]
@Andrews54757 Im still fixing it, there's a problem im trying to resolve.

**Comment by Andrews54757** [comment]
FJo3ye4l5HqvCuIIe2u4

**Comment by Andrews54757** [comment]
@LegitSoulja http://live.ogarul.io/?data=_ab. (delete after see)

**Comment by Andrews54757** [comment]
Never mind, it didn't duplicate

**Comment by LegitSoulja** [comment]
@Andrews54757 I'm having issues with SQL syntax, Trying to figure out the problem

**Comment by Andrews54757** [comment]
It is probably at ` $q = "UPDATE `keys` SET (`owner`) VALUE ('".$newOwner."') WHERE `uid`='".$uid."'";`

**Comment by LegitSoulja** [comment]
It's not that anymore

Look at core/keyGen.php

**Comment by LegitSoulja** [comment]
This error keeps being thrown > net::ERR_INCOMPLETE_CHUNKED_ENCODING

**Comment by Andrews54757** [comment]
No, it is wrong. Shouldn't it be ``$q = "UPDATE `keys` SET `owner` = '".$newOwner."' WHERE `uid`='".$uid."'";``

**Comment by LegitSoulja** [comment]
@Andrews54757 both ways work with it's key, and value

But refresh the config file, I been changed it back as that.

**Comment by Andrews54757** [comment]
Now the generate button is redirecting again

**Comment by LegitSoulja** [comment]
False statement

**Comment by LegitSoulja** [comment]
I haven't even touched javascript

**Comment by Andrews54757** [comment]
@LegitSoulja I found this: `` while($row = mysqli_fetch_array){``, on line 121. Shouldn't it be `` while($row = mysqli_fetch_array($results)){``

**Comment by LegitSoulja** [comment]
@Andrews54757 Thanks for pointing that out. I fixed it, but i don't think that's the issue :/

**Comment by LegitSoulja** [comment]
Wait it works

**Comment by LegitSoulja** [comment]
FJo3ye4l5HqvCuIIe2u0

Try to steal it

**Comment by Andrews54757** [comment]
And you didn't add the 20 char check

**Comment by LegitSoulja** [comment]
The 20 char check is in javascript

**Comment by Andrews54757** [comment]
And it didn't give me a message saying it stole the key, but I have it

**Comment by LegitSoulja** [comment]
Look at the keys

it's weird. Why isn't your uid same as mines if you stole it?

**Comment by Andrews54757** [comment]
FJo3ye4l5HqvCuIIe2u4 is a test uid I created. It is not the one I stole

**Comment by LegitSoulja** [comment]
Try stealing FJo3ye4l5HqvCuIIe2u0

**Comment by LegitSoulja** [comment]
now its trading keys?

**Comment by Andrews54757** [comment]
I did it, but it wasn't stolen. Steal mine: FJo3ye4l5HqvCuIIe2u0.

**Comment by Andrews54757** [comment]
After you reload the page, after you steal it, it dissapears

**Comment by Andrews54757** [comment]
you stole it

**Comment by LegitSoulja** [comment]
There's a fault in the system, when it stole it, it said the key was generated, not stolen :/

**Comment by LegitSoulja** [comment]
ohh i know why

**Comment by LegitSoulja** [comment]
Everything seems to be working now. And the key will always be disabled, unless it's stolen and activated.

**Comment by LegitSoulja** [comment]
look at live _ab, i gave you a solution to your problem.

**Comment by Andrews54757** [comment]
What problem

**Comment by LegitSoulja** [comment]
@Andrews54757 duplicate output from the SQL

**Comment by LegitSoulja** [comment]
@Andrews54757 You understand how the site works now right?

**Comment by LegitSoulja** [comment]
I'm gonna be leaving tomorrow for my weeks at Dubai. I'll have my laptop with me, but not to sure about the internet. I'll probably have to use my hotspot on my phone (That's even if I can get service).

But if there's anything else needed to be done let me know. I got 6-7 more hours before I crash to bed.

**Comment by Andrews54757** [comment]
@LegitSoulja Take a long rest. I won't mind, I figured out most the structure for the site.

**Comment by LegitSoulja** [comment]
@Andrews54757 Yea, when I get back, I'll see how I can make the site better than it is now.

Remember, the site is bootstrap, so I might just turn the entire site into bootstrap content. But I need to think about how the site will be laid out, unless you like the way it is now.

Altho, there's a few things I need to fix with css, cause the site is still buggy when the browser size changes.

**Comment by LegitSoulja** [comment]
@Andrews54757 

```
source\entities\playerCell.js:25
        this.skin = owner.skinHandler.skin;
                                     ^

TypeError: Cannot read property 'skin' of undefined
    at new cell (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\entities\playerCell.js:25:38)
    at Main.addNode (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\core\main.js:1006:21)
    at Main.spawn (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\core\main.js:515:14)
    at childService.action (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\core\childService.js:83:23)
    at data.forEach (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\core\childService.js:126:22)
    at Array.forEach (native)
    at childService.onData (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\core\childService.js:119:14)
    at childService.<anonymous> (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\core\childService.js:39:18)
    at ChildHolder.<anonymous> (C:\Users\LegitSoulja\Desktop\Project-Nehemiah-master\source\core\childHolder.js:30:63)
    at emitTwo (events.js:106:13)
```

**Comment by Andrews54757** [comment]
@LegitSoulja Everything works fine. It seems like it didn't update properly. I hope you didn't use the update command. Thats is not finished yet.

**Comment by Andrews54757** [comment]
Also, go on gitter

**Comment by Wawy123** [comment]
wont work ;/

**Comment by Andrews54757** [comment]
Too bad then

**Comment by Andrews54757** [comment]
@LegitSoulja I was thinking about something. Should there be two versions of OpenAgar? One for the community, where you do not need a key to use, but is limited as well as not being supported by us (only updated by prs from the community).

**Comment by LegitSoulja** [comment]
@Andrews54757 No.

**Comment by LegitSoulja** [comment]
OgarUl is for the community. Let them have that.

**Comment by suprix** [comment]
hey, I need help... I put my key in key.txt and after i typed "node index.js" it says again 
![image](https://cloud.githubusercontent.com/assets/24485754/21069370/7376f3e8-be79-11e6-8089-148d50b9d2e2.png)

**Comment by Andrews54757** [comment]
Your key is not your id. We will not guide you. Read the readme properly

**Comment by LegitSoulja** [comment]
I like how he hid his ID lol

**Comment by PrinceDark9243** [comment]
i generated key but isnt working why?

**Comment by LegitSoulja** [comment]
@PrinceDark9243 make sure you update OpenAgar.

**Comment by Atomix23** [comment]
Guys my key is not working ._.
**Welp!**
It was working yesterday when andrews gave me1 i started server using it but i cant use it today. Is it no longer avaible!? It says like my key is invalid!

**Comment by Andrews54757** [comment]
give me your id again

**Comment by Atomix23** [comment]
is it secure to send it here!?

**Comment by Andrews54757** [comment]
Yes.

**Comment by Atomix23** [comment]
24458572

**Comment by Andrews54757** [comment]
That is not your id

**Comment by Atomix23** [comment]
If you have any problems just screenshot it, and report it here with your id (24458572)

**Comment by Andrews54757** [comment]
No, I mean your server id

**Comment by Andrews54757** [comment]
It looks like however, you registered MhdxpdF7wAJwyJmeBNBD

**Comment by Atomix23** [comment]
oh this UID
yes this is it

**Comment by Atomix23** [comment]
do i have to disable it now?

**Comment by Andrews54757** [comment]
no

**Comment by Andrews54757** [comment]
When it says invalid key, what does it show for your uid?

**Comment by Andrews54757** [comment]
Make sure that the key in key.txt is 129900328728

**Comment by Atomix23** [comment]
but it is

**Comment by Andrews54757** [comment]
When it says invalid key, what does it display?

**Comment by Atomix23** [comment]
[OpenAgar]Invalid key!, make sure you have the right key! Your id is: false

**Comment by Andrews54757** [comment]
Let me guess, you changed the name of the directory where OpenAgar runs in?

**Comment by Atomix23** [comment]
Oh is bcuz of this oh nooo i just wanet it be on the desktop it was on disc C:/

**Comment by Andrews54757** [comment]
If so, delete a file called `backup`

**Comment by Andrews54757** [comment]
Then your new directory should work

**Comment by Atomix23** [comment]
then install dependancies again?

**Comment by Andrews54757** [comment]
No

**Comment by Atomix23** [comment]
i deleted file called _backup but again not working

**Comment by Andrews54757** [comment]
I just updated the UID script, so it now displays the message `Your id will show false. This is because you probably renamed the directory. It is a protection feature for a file called _backup. Because the backup file is for offline uses. In order to change directory names, please delete the file called backup and re run online. The backup file will auto generate. This may also be caused by you using sudo at first, then by not using it and vise versa`

**Comment by Andrews54757** [comment]
It probably still exists. Go inside the OpenAgar folder and delete the file `_backup`

**Comment by Atomix23** [comment]
it dont lemme show u <url=http://i.imgur.com/cQ5AvA9.png>here</url>

**Comment by Andrews54757** [comment]
Then delete a file called `_mcuid` to reset your id. You will have to deactivate your old one and activate your new one.

**Comment by Atomix23** [comment]
how i will know what is my new

**Comment by Andrews54757** [comment]
Re run the program

**Comment by Atomix23** [comment]
oh i updated it and it says this
module.js:471
    throw err;
    ^

Error: Cannot find module './lib/kickbots.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Atomix\Desktop\OpenAgar-master\source\commands\index.js:8:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by Andrews54757** [comment]
@Atomix23 Redownload. I fixed it

**Comment by Atomix23** [comment]
i redownloaded it but now it gave me new uid
what now its LunUaVI0RwgVmI9sKL0x

**Comment by LegitSoulja** [comment]
@Andrews54757 hola,

Reading above about failed directories is that to prevent project stealers? (Who shares OpenAgar with a pre-installed key)?

**Comment by Atomix23** [comment]
@LegitSoulja ,bro u have to hear this!
in the chat: http://forum.ogarul.io
Valkyy: so how exactly does opbyip.txt work? I typed in my ipv4 connection ip, doesn't op me when I join in the server.
lol

**Comment by Andrews54757** [comment]
@LegitSoulja I made sure that OpenAgar is hard to comprimise

**Comment by LegitSoulja** [comment]
@Andrews54757 I've added an addition to the site config. There's a file called bypass.txt. Each line you put the link of a github account.

This allows us to give exclusive access to a certain person instead of increasing the cap, which can be risky.

**Comment by Ckicky** [comment]
YOU said 30 people to will be able to register. BUT now, as I see, It only has 22 members but when I try to login, It said that the maximum number of member has reached :/ . Makes damn sense

**Comment by Ckicky** [comment]
![makes fkin sense](https://cloud.githubusercontent.com/assets/18949821/21580511/cd79f5b8-d02e-11e6-83fc-0acf4c4d8c17.PNG)

**Comment by Ckicky** [comment]
![after pressing sign in with Github](https://cloud.githubusercontent.com/assets/18949821/21580514/09fe8b84-d02f-11e6-88b8-dc040f5485b6.PNG)

**Comment by LegitSoulja** [comment]
Nobody gave an exact date when the cap increase. And it won't be soon, 

In another week. Maybe more, or a month, or more.

**Comment by LegitSoulja** [comment]
Plus, I'm remaking the site, no more accounts until I'm done.

**Comment by Ciao121** [comment]
Hi,
I do not understund the key system reason. I can understand if a "membership" is required to collaborate to the project. But why a key is required, in example, to just "test" the code?

**Comment by Andrews54757** [comment]
@Ciao121 A key is required to keep this project semi private. Take a look at our previous project, OgarUL. That project collapsed on itself.

**Comment by Andrews54757** [comment]
@Ciao121 Since everyone could use the code, people who dont know how to run it (computer noobs), wasted a bunch of our time. About 80% of issues in OgarUL was related to things that they could find out by searching google or previous issues. We couldnt do any work at all because of this time waste

**Comment by Andrews54757** [comment]
@Ciao121 Just for the purpose of you looking at the OgarUL issues, I will open them back up again so you can see just how bad it was. Notify me when you are done looking at them

**Comment by Andrews54757** [comment]
@Ciao121 , a list of some issues I found:

1. https://github.com/AJS-development/Ogar-unlimited/issues/1401
2. https://github.com/AJS-development/Ogar-unlimited/issues/1398
3. https://github.com/AJS-development/Ogar-unlimited/issues/1392
4. https://github.com/AJS-development/Ogar-unlimited/issues/1389
5. https://github.com/AJS-development/Ogar-unlimited/issues/1385
6. https://github.com/AJS-development/Ogar-unlimited/issues/1370
7. https://github.com/AJS-development/Ogar-unlimited/issues/1367
8. https://github.com/AJS-development/Ogar-unlimited/issues/1362
9. https://github.com/AJS-development/Ogar-unlimited/issues/1349
10. https://github.com/AJS-development/Ogar-unlimited/issues/1331
11. https://github.com/AJS-development/Ogar-unlimited/issues/1323
12. https://github.com/AJS-development/Ogar-unlimited/issues/1324
13. https://github.com/AJS-development/Ogar-unlimited/issues/1300
14. https://github.com/AJS-development/Ogar-unlimited/issues/1293
15. https://github.com/AJS-development/Ogar-unlimited/issues/1292

**Comment by Andrews54757** [comment]
We had so much of those bad issues, we had to have more than 12 members to take care of them. We were becoming more of a support service for computer problems instead of developers

**Comment by Andrews54757** [comment]
@Ciao121 Now do you understand why we have a key system?

**Comment by LegitSoulja** [comment]
Short: 

This project is private/public only to those who obtain with having potential knowledge of use. We've wasted time with support, (With non technical based questions about our project, but more like question you should learn or have knowledge of or rather use another source as of "Google".

The links above to those issues, Andrew only touch 0.03% out of 100.0... Github isn't for that, plus the community got way to big and left a negative impact on the side for no support.

Basically we moved support to a secluded location which is now open and could've been well known discovered as of 2 weeks ago. (Because of OpenAgar). 

We're basically trying atleast to start a new branch, new community, and just keep things under control. Which we have full control over.

**Comment by Ciao121** [comment]
Ok, now it's clear to me. I think it would be better (if possible) to only restrict access to issues/support here. Because a key to just "run" the code will also limit, IMOO, good questions/contributions. But maybe there is no such option on GH.

Thank you for your replies. I'll look for the cap increase! :)
@Andrews54757 I looked OgarUL issues.

**Comment by LegitSoulja** [comment]
@Andrews54757 Whenever you decide to change the usercap you can. I am now finished with the new site layout, and now im doing major check for bugs because there's alot, but i've been working for about an hour or two fixing them before release, but let me if you find some vulnerabilities.

All the code is different from the site btw.

**Comment by Andrews54757** [comment]
@LegitSoulja Wow, that looks awesome! And you should increase the cap, I don't know how to send the notification letters. Increase it to 50

**Comment by Andrews54757** [comment]
@LegitSoulja I think I know what the problem is with ``fsockopen``. http://stackoverflow.com/questions/8739205/unable-to-connect-with-fsockopen-in-php-connection-timed-out.  I found out my ip doesn't work either when testing.

**Comment by Andrews54757** [comment]
godaddy blocks fsockopen

**Comment by Andrews54757** [comment]
https://www.godaddy.com/help/do-you-support-fsockopen-287

**Comment by Andrews54757** [comment]
They only allow ports 80 and 443

**Comment by Andrews54757** [comment]
😠

**Comment by Andrews54757** [comment]
@LegitSoulja I think we will have to use VPS/our own server. We should set it up so we continue to use go daddy, but all fsockopen requests will be forwarded to the VPS server

**Comment by LegitSoulja** [comment]
@Andrews54757 I think I can come up with a solution.

**Comment by Ciao121** [comment]
What's the problem? Maybe someone could help finding a slution.

**Comment by LegitSoulja** [comment]
@Ciao21 it's nothing important.

**Comment by LegitSoulja** [comment]
@Andrews54757 I'll host a site in which will receive requests from our Live requests. A VPS isn't needed

**Comment by LegitSoulja** [comment]
@Ciao121 since I'm going to postpone site user cap, I'll give you exclusive access to use the site & generate keys.

**Comment by LegitSoulja** [comment]
Only thing you need to do is visit the link above

**Comment by Ciao121** [comment]
Done. Thank you.
Seems it works fine. I like the dashboard! I'm looking at it.
Generated key works (no key error at server start). Having another problem (a missing module) but I'm going to investigate it.
Thank you again!

**Comment by Andrews54757** [comment]
@LegitSoulja I will increase the cap to 50

**Comment by Andrews54757** [comment]
@LegitSoulja You send the emails, I dont know how to

**Comment by LegitSoulja** [comment]
@Andrews54757 I'll increase it since im working on something and don't want to overwrite your current change.

And i'll send emails once I publish the next bug fix for the sites.

**Comment by LegitSoulja** [comment]
And you said 50, not 60

**Comment by LegitSoulja** [comment]
and nvm, I can merge your changed automatically. I didn't know I could.

**Comment by LegitSoulja** [comment]
@Andrews54757 1,294 emails has been sent, including me and you.

**Comment by Ciao121** [comment]
Hi,
there i a little problem with the email that an user receive about key activaction. When a new key is created, the uid field in the sent mail is blank:

```
Here's your new generated registration for your OpenAgar server.
UID: ().
Key: (184472861236) 
```
The same field is ok in the mail that is sent when a key is deactivated. But maybe, in this case, the email objects should be different from "Your generated key".

**Comment by LegitSoulja** [comment]
@Ciao121 thanks for reporting, I'll look into the issue.

**Comment by LegitSoulja** [comment]
Issue fixed due to a typo

**Comment by Tempation103** [comment]
where do the key generator supposed to be

**Comment by Andrews54757** [comment]
@Tempation103 That is a noob question that is answered in the readme

**Comment by LegitSoulja** [comment]
@Andrews54757 not only the readme, but this issue in general lol.

I think we should ignore/remove questions like this.

**Comment by LegitSoulja** [comment]
#### Tutorial video 

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/6B__wxcS8hU/0.jpg)](https://www.youtube.com/watch?v=6B__wxcS8hU)
