### ISSUE TITLE
http://opnagar.us/?page=keys Not working

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/OpenAgar#32]
I Tried to generate my key with it, but it says my key is incorrect...
UID: ns7zWVcY5YTuVLUa5sSu
GENERATED KEY: 416931339819
Btw, can i have my Correct key? I want to test some things out

**Comment by Andrews54757** [comment]
I changed the key algorithm

**Comment by Andrews54757** [comment]
So it won't work

**Comment by LegitSoulja** [comment]
@Andrews54757 You could've told me :/ Can I have it?

**Comment by LegitSoulja** [comment]
@SharkFinPro I'll remove the key from your account. Don't generate it until the algorithm is updated.

**Comment by LegitSoulja** [comment]
@SharkFinPro also, I'll allow you to create 5 keys max just because you're somewhat part of AJS.

**Comment by Andrews54757** [comment]
@LegitSoulja I am going to wait for a while for the new keys to come out. However, I did update the link I showed you a while ago.

**Comment by Andrews54757** [comment]
You can give people exclusive access, but not public yet.

**Comment by Andrews54757** [comment]
I am tired of work-stealers

**Comment by Andrews54757** [comment]
BTW, did you check gitter?

**Comment by LegitSoulja** [comment]
Ok, I'll set key limits to 0 for new people that register. And no i haven't

**Comment by LegitSoulja** [comment]
@SharkFinPro You can now generate your keys!.

**Comment by LegitSoulja** [comment]
Closing issue

**Comment by batak27** [comment]
key alamıyorum siteye bağlanmıyo key verin

**Comment by FantasyIsBae** [comment]
>key alamıyorum siteye bağlanmıyo key verin

TRANSLATION FROM TURKISH : I can not get the key
