### ISSUE TITLE
grid is not working correctly

### ISSUE THREAD

**Issue by seifgaming** [AJS-development/OpenAgar#33]
thats all 
![capture](https://cloud.githubusercontent.com/assets/20099252/21029012/65af3ab0-bda0-11e6-90af-4fb8875cc3d1.PNG)

**Comment by LegitSoulja** [comment]
I thought you meant there was a grid bug for OpenAgar in which I told you to report it here, however

since it is OgarUnlimited there's nothing we can do. There's is an option where you can disable the grid.

**Comment by Andrews54757** [comment]
Looks like it is working fine. However, you have violated the rules of the issues section. It clearly says that you should think before you post. You posted on OpenAgar, an issue for OgarUL. You should have posted it here: http://forum.ogarul.io/.

**Comment by LegitSoulja** [comment]
@Andrews54757 It was my fault. He didn't violate anything.

**Comment by Andrews54757** [comment]
Ok.
