### ISSUE TITLE
mock-server

### ISSUE THREAD

**Issue by seifgaming** [AJS-development/OpenAgar#34]
![capture](https://cloud.githubusercontent.com/assets/20099252/21050580/32ae9afa-be24-11e6-864d-84882cd1a284.PNG)
what should i do i afraid to redownload cuz my key will change and i wont be able to get new key what should i do its openagar

**Comment by Andrews54757** [comment]
@seifgaming Your key never changes. You see this message because your server is outdated. However though, your key won't work for the new update. It is because we are managing things at http://opnagar.us/. You have to register keys there now

**Comment by seifgaming** [comment]
i updated it but it say invalid key >:( i have to wait next year to get my key

**Comment by seifgaming** [comment]
my id is IwOkHw0cHcDL9zqQ689R

**Comment by Andrews54757** [comment]
171677103258
