### ISSUE TITLE
you and me got bored

### ISSUE THREAD

**Issue by seifgaming** [AJS-development/OpenAgar#37]
hello mr:andrew i know you got bored from me asking my key every time but you guys updated open agar 
and there is no update command so i have nothing to do just i can download the new version from github and it will ask for key again 
please fix this problem about keys i really loved openagar+ i heard lately that you guys added skins congrates!
i want key please my id : VlUl3ooqKGvygwFbpEmT

**Comment by LegitSoulja** [comment]
@seifgaming I've told you, when you update OpenAgar just overwrite it's content. 

If you would've listened you wouldn't have had any issues with loosin your key. You have been given more than one key without listening, therefor nomore will be given

**Comment by LegitSoulja** [comment]
@Andrews54747 Also, make sure the update command doesn't effect the UID's. I'm pretty sure it doesn't but I'm just making sure

**Comment by LegitSoulja** [comment]
And deactivate his keys aswell. Also, I need to add a site labeling system so we can know what each UID is used for.

**Comment by Andrews54757** [comment]
@seifgaming . your uid will never change. even if you update. so please use your old key

**Comment by seifgaming** [comment]
![capture](https://cloud.githubusercontent.com/assets/20099252/21118377/4b12dcb0-c0c6-11e6-9224-07d3cd14f0e2.PNG)
sorry guys 1 last key please please please cuz i havent understand legit when he told me overwrite 
and mr:andrew no my id change every time

**Comment by LegitSoulja** [comment]
@seifgaming repeat after me

"I will not ask for another key, and I will make sure I don't delete OpenAgar content when updating, but instead replace its content"

As of looking, the update command does work with the recent update. So in the future, use that command to update.

**Comment by Andrews54757** [comment]
@LegitSoulja The command works. the reason why his thing doesnt work is because it is probably not registered  in opnagar.us he is probably a beta tester from when we didnt have the website set up

**Comment by seifgaming** [comment]
I will not ask for another key, and I will make sure I don't delete OpenAgar content when updating, but instead replace its content 
lol

**Comment by seifgaming** [comment]
VlUl3ooqKGvygwFbpEmT
my id

**Comment by Andrews54757** [comment]
You generate your id by yourself. http://opnagar.us

**Comment by seifgaming** [comment]
Sorry, but we are no longer accepting accounts. Catch us again soon when we increase the cap!.

**Comment by LegitSoulja** [comment]
@seifgaming one second while I add you to the bypass list

**Comment by Andrews54757** [comment]
I already did a while ago @LegitSoulja

**Comment by LegitSoulja** [comment]
Ok he should be able to register now

**Comment by Andrews54757** [comment]
And are you sure you want to keep the bypass.txt file as a txt? Wouldn't it be secure if it was php?

**Comment by Andrews54757** [comment]
But whatever

**Comment by LegitSoulja** [comment]
@Andrews54757 sooner or later when I get back home I'll start working on the back end admin panel. Bypasses will be stored in SQL

**Comment by seifgaming** [comment]
thanks it worked guys

**Comment by seifgaming** [comment]
yayyyyy open agar worked your the best guys

**Comment by seifgaming** [comment]
lol andrew is....awesome

**Comment by LegitSoulja** [comment]
@Andrews54757 and it only contains github profile urls. No security is needed, and plus its temporary

**Comment by Andrews54757** [comment]
Ok then

**Comment by LegitSoulja** [comment]
@Andrews54757 check gitter when you have time
