### ISSUE TITLE
How to make work :c

### ISSUE THREAD

**Issue by AlexByte918** [AJS-development/OpenAgar#38]
Tittle

**Comment by LegitSoulja** [comment]
@AlexByte918 You can read... Instead of asking questions.

**Comment by LegitSoulja** [comment]
@AlexByte918 besides, there's no way possible for you to "Make work"

**Comment by Andrews54757** [comment]
@AlexByte918 I clearly put on the issues template and rule not to do this. Therefore you are banned permanently


OFFENSE:
> Disobeying issues section rules. And don't say you didn't know. Ignorance is a crime of itself


Today I hereby declare you BANNED from AJS indefinitely
> Banned on Dec 14.

**Comment by LegitSoulja** [comment]
@Andrews54757 check gitter asap
