### ISSUE TITLE
glitch?

### ISSUE THREAD

**Issue by Wawy123** [AJS-development/OpenAgar#39]
i runed it and wont spawn
http://imgur.com/a/R5Eho

**Comment by Andrews54757** [comment]
Mobile support hasnt been completed. you are using a tablet

**Comment by LegitSoulja** [comment]
I don't think that's mobile. Those mobile button appears for desktop aswell(glitch). It's annoying, but I barely don't even play

**Comment by Wawy123** [comment]
i use tablet like pc in one ;)

**Comment by LegitSoulja** [comment]
@Andrews54757 I got a challenge for you, try to decode this :) 
http://old.ogarul.io/live.js

And im back home.

**Comment by Andrews54757** [comment]
Too easy
