### ISSUE TITLE
Id problem

### ISSUE THREAD

**Issue by Ciao121** [AJS-development/OpenAgar#43]
Hi,
I think there is a problem a problem with the id/key system. After a working setup I think those steps should reproduce the problem. I'm on WIN 10

1) Shutdown the OpenAgar server.
2) **Rename the folder containing the OpenAgar files** (mine was OpenAgar-master and I renamend it to OpenAgar-master_key). I renamed it to be sure files are not overwritten if I download the archive again.
3) Restart the server
At this point this error fire: "Something went wrong. So we reset your id. Your new id: etc etc etc" and key.txt is overwitten with the original one ("Put your key here").

Renaming the folder to the original name does not solve. The id is "gone" forever so the assigned key does not work anymore.

Trying to see if it is related to this:
https://github.com/AJS-development/OpenAgar/issues/7

**Comment by Ciao121** [comment]
Tried removing _backup and _mcuid but it seems it does not "revert" to the "original" id. Each time it gives me a **new** id.

**Comment by LegitSoulja** [comment]
@Cliao121, At this time. There should be 2 files

* backup
* mcuid

One can be found in the main directory, and source/controller. Delete them, Rename your folder, or move the files inside to another location.

And when was the last time you've downloaded OpenAgar? Keep it updated.

**Comment by LegitSoulja** [comment]
Best bet is download a fresh version in start in another directory.

**Comment by Ciao121** [comment]
Just tried (anyway I downloaded it yesterday), but the id it gives me is different from the one I ued to generate the key. Also, deleting the mcuid without renaming the folder cause a new (and different) id generated every time.

**Comment by Ciao121** [comment]
This is the outpuf from the t.js script used in the other thread

```
C:\Users\ivan\Desktop\OpenAgar-master>node t.js
Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
00:26:82:76:c5:3b
win32
x64
Windows_NT

C:\Users\ivan\Desktop\OpenAgar-master>node t.js
Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
00:26:82:76:c5:3b
win32
x64
Windows_NT
```

**Comment by LegitSoulja** [comment]
@Ciao121 Exactly. you said you deleted the backup, and the mcuid file already so you have lost your uid, and need to generate another key. You can do this be disabling an activated key, to generate another.

The t `script` wasn't needed. This is a normal caused bug with OpenAgar.

**Comment by Ciao121** [comment]
Oh ok!!! I was worried to disable my key... I did not figured that disabling a key I could generate a new one!
Thanks!

**Comment by LegitSoulja** [comment]
@Ciao121 Yes. You can enable, and disable keys. If you disable a key it cannot no longer be used unless activated again. You are only allowed to have one active key, as to what was assigned.

In the future we will allow people to have more than one key, but we need to figure out a way to allow. Meaning, instead of peopling buying what is a way they can get the ability to generate more keys. Maybe after the stats come to the servers I can start calculating server player counts and reward people with keys to run more than 1 server haha

**Comment by Andrews54757** [comment]
@LegitSoulja The bug is fixed, in the way that the id is reset when you rename the folder, other than it crashing.

**Comment by Andrews54757** [comment]
@Ciao121 This is on purpose. I implemented the key system a long time ago before OpenAgar, in the days of OgarUl. One of the security features was that directories cant be changed.
