### ISSUE TITLE
Bullet setOwn

### ISSUE THREAD

**Issue by Ciao121** [AJS-development/OpenAgar#45]
When an user shoot a bullet this error occours:
"Cannot read property 'setOwn' of undefined"
I'm not really a programmer. I tried adding
`this.own = owner;`
after
`this.type = 5;`
in entities/bullet.js
Now the error is no more present. But I really don't know if my "fix" is the right one (also because I'm not sure about what bullets are supposed to do ^_^)

**Comment by Andrews54757** [comment]
Yes, thanks for notifying me of this error.
