### ISSUE TITLE
Server won't start for some reason.

### ISSUE THREAD

**Issue by alktbihd** [AJS-development/OpenAgar#47]
Here is the log: 

> [OpenAgar] Starting OpenAgar V3.8.0
> [OpenAgar] Loaded server configs
> [OpenAgar] Loaded ban file and cleaned it
> [OpenAgar] Loaded custom skins
> [OpenAgar] Loaded game server configs
> undefined
> undefined

Solution?

**Comment by LegitSoulja** [comment]
@alktbihd Let try this,

Are you currently running any plugins?

**Comment by alktbihd** [comment]
nope fresh start

**Comment by alktbihd** [comment]
installed, put my key then started

**Comment by Andrews54757** [comment]
Is your id OMh7xHzOKXQsZDn1NDcI?

**Comment by Andrews54757** [comment]
Are you using an invalid gamemode?

**Comment by alktbihd** [comment]
yes

**Comment by Andrews54757** [comment]
@alktbihd ?

**Comment by alktbihd** [comment]
nope
its a fresh start

**Comment by alktbihd** [comment]
dint edit nothing

**Comment by Andrews54757** [comment]
is OMh7xHzOKXQsZDn1NDcI your id?

**Comment by alktbihd** [comment]
yes

**Comment by Andrews54757** [comment]
Yeah, I saw your id on our error logs

**Comment by Andrews54757** [comment]
However, nothing is on the log that can help:

>{"0":"OMh7xHzOKXQsZDn1NDcI","uid":"OMh7xHzOKXQsZDn1NDcI","1":"2147483647","key":"2147483647","2":"","message":"","3":"","stack":"","4":"3.8.0","version":"3.8.0"}

**Comment by alktbihd** [comment]
so i need a new id?

**Comment by Andrews54757** [comment]
No

**Comment by Andrews54757** [comment]
@alktbihd Do this for me, delete lines https://github.com/AJS-development/OpenAgar/blob/master/source/core/controller.js#L61-L63 in your copy

**Comment by Andrews54757** [comment]
Then run again

**Comment by Andrews54757** [comment]
What does the console say then @alktbihd ?

**Comment by alktbihd** [comment]
/root/OpenAgar/source/core/childManager.js:37
        if (this.cpus.length <= 1) throw "Your computer must have more than one core in order to run this program"
                                   ^
Your computer must have more than one core in order to run this program

**Comment by Andrews54757** [comment]
Wow. Your computer is bad

**Comment by alktbihd** [comment]
server*

**Comment by Andrews54757** [comment]
Sorry, but OpenAgar uses more than 1 cpu core.

**Comment by Andrews54757** [comment]
You can however, override that check to use it, but it wont be so optimised

**Comment by Andrews54757** [comment]
You will also have to edit other parts

**Comment by Andrews54757** [comment]
You will also have to edit line 51 of childManager.js

**Comment by Andrews54757** [comment]
Change
```
        if (this.childs.size < this.cpus.length - 1) {
```

to 

```
        if (this.childs.size < this.cpus.length) {
```

**Comment by FlamePlayerTR** [comment]
Hey Andrews54757 Plz ready tutoriol video to create server I trying 2 months but I cant plz record the video plzzz

**Comment by LegitSoulja** [comment]
@FlamePlayerTR Really? This is the main reason why I deleted it.

If you can't follow the simple tutorial, then a video wouldn't help neither. The only option for you is to stop trying, and let those people who understands how nodejs use this project.
