### ISSUE TITLE
ID Reseting

### ISSUE THREAD

**Issue by TrevorCow** [AJS-development/OpenAgar#48]
Every time I start OpenAgar it returns: "[OpenAgar]Something went wrong. So we reset your id. Your new id:" and gives me a new ID. I have tried chmoding everything to 777 and running as root. Any suggestions?

**Comment by Andrews54757** [comment]
Did you change the name of the openagar directory?

**Comment by TrevorCow** [comment]
No

**Comment by Andrews54757** [comment]
Tell me exactly what you did to produce this.

**Comment by TrevorCow** [comment]
Nothing, fresh install

**Comment by TrevorCow** [comment]
I just deleted everything and retried. still just giving me new id.

**Comment by Andrews54757** [comment]
How did you launch the server, tell me with description

**Comment by TrevorCow** [comment]
I used git to make an OpenAgar dir, then cd'ed into it, ran npm install, then node index.js, then gen and copied key, then ran again. It then doesn't fully start, and gives me a new id telling me something went wrong.

**Comment by Andrews54757** [comment]
Does your machine have mac address spoofing?

**Comment by TrevorCow** [comment]
Maybe, i have a VPS. I don't know why that would be enabled...

**Comment by Andrews54757** [comment]
This has happened before: #7

**Comment by Andrews54757** [comment]
Run this script twice, and report the results please: 
[t.js.zip](https://github.com/AJS-development/OpenAgar/files/683407/t.js.zip)

**Comment by TrevorCow** [comment]
I deleted the whole folder, inculding the backup and muid file. Still happens...

**Comment by Andrews54757** [comment]
Try running the script twice

**Comment by TrevorCow** [comment]
ok

**Comment by TrevorCow** [comment]
root@TrevorCow:~/Servers/OpenAgar# node t.js 
Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
undefined
linux
x64
Linux
root@TrevorCow:~/Servers/OpenAgar# node t.js 
Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
undefined
linux
x64
Linux

**Comment by Andrews54757** [comment]
@TrevorCow It looks like your machine doesnt have a mac address. To confirm, run this script and give me the results:

```

console.log(os.networkInterfaces())

```

**Comment by TrevorCow** [comment]
root@TrevorCow:\~/Servers/OpenAgar# node t.js 
Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz
undefined
linux
x64
Linux
{ lo: 
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true } ],
  venet0: 
   [ { address: '127.0.0.2',
       netmask: '255.255.255.255',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: false },
     { address: '2001:19f0:200:2d91::3714:6c7b',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '48:4c:e2:39:9b:7f',
       scopeid: 0,
       internal: false } ],
  'venet0:0': 
   [ { address: '45.63.2.47',
       netmask: '255.255.255.255',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: false } ] }

**Comment by TrevorCow** [comment]
Do you suggest i spoof it?

**Comment by Andrews54757** [comment]
@TrevorCow This is what mine looks like:
```
{ lo0: 
   [ { address: '127.0.0.1',
       netmask: '255.0.0.0',
       family: 'IPv4',
       mac: '00:00:00:00:00:00',
       internal: true },
     { address: '::1',
       netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 0,
       internal: true },
     { address: 'fe80::1',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 1,
       internal: true } ],
  en0: 
   [ { address: 'fe80::404:28fc:3f24:3903',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'c4:b3:01:c6:0f:bf',
       scopeid: 4,
       internal: false },
     { address: '192.168.1.8',
       netmask: '255.255.255.0',
       family: 'IPv4',
       mac: 'c4:b3:01:c6:0f:bf',
       internal: false } ],
  awdl0: 
   [ { address: 'fe80::f8ca:c5ff:fe53:bd60',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: 'fa:ca:c5:53:bd:60',
       scopeid: 9,
       internal: false } ],
  utun0: 
   [ { address: 'fe80::31b6:da62:6562:3cb',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 10,
       internal: false } ],
  utun1: 
   [ { address: 'fe80::af22:c3b7:960e:137',
       netmask: 'ffff:ffff:ffff:ffff::',
       family: 'IPv6',
       mac: '00:00:00:00:00:00',
       scopeid: 11,
       internal: false } ] }
```

**Comment by Andrews54757** [comment]
@TrevorCow I will fix it soon

**Comment by TrevorCow** [comment]
Ok I'll just have to update then? Thanks andrew :)

**Comment by Andrews54757** [comment]
@TrevorCow Fixed

**Comment by TrevorCow** [comment]
It is still happening @Andrews54757

**Comment by Andrews54757** [comment]
Git pull

**Comment by TrevorCow** [comment]
I did git clone again

**Comment by TrevorCow** [comment]
"Already up-to-date"

**Comment by TrevorCow** [comment]
Even if I don't put a key it errors @Andrews54757

**Comment by Andrews54757** [comment]
Update again, I changed it

**Comment by TrevorCow** [comment]
nope :/ @Andrews54757

**Comment by TrevorCow** [comment]
Any ideas? @Andrews54757

**Comment by Andrews54757** [comment]
Nope

**Comment by TrevorCow** [comment]
Darn :/ Would it work if I spoofed a mac address? @Andrews54757

**Comment by Andrews54757** [comment]
nope

**Comment by Andrews54757** [comment]
Its not because of that

**Comment by TrevorCow** [comment]
Oh, what is the reason then?

**Comment by LegitSoulja** [comment]
@TrevorCow ok, this VPS. Yours? Or renting?

**Comment by LegitSoulja** [comment]
If renting, contact your hosting about your MAC address usage.

I think it's silly that it's needed, but stronger security I guess.

**Comment by Andrews54757** [comment]
@LegitSoulja , without this protection, it would mean that people would be able to sell openagar copies

**Comment by TrevorCow** [comment]
@LegitSoulja @Andrews54757 shouldn't I be able to set it myself?

**Comment by Andrews54757** [comment]
@TrevorCow Solution: Dont use a vps. Use a real dedicated server you have full control over

**Comment by Andrews54757** [comment]
@TrevorCow This is my server:

![61ot7cbcbel _sx522_](https://cloud.githubusercontent.com/assets/13282284/21655099/8c17e490-d286-11e6-8021-76b1d6708df2.jpg)

**Comment by LegitSoulja** [comment]
What is that lol

**Comment by FantasyIsBae** [comment]
https://www.qnap.com/
