### ISSUE TITLE
Cant connect ?

### ISSUE THREAD

**Issue by xMuratY** [AJS-development/OpenAgar#52]
Output ; 

`  [OpenAgar] Server listening on port 1579
[OpenAgar] Registered server to stats! It is now accessable at http://opnagar.us/server/agarwo`

All is well but clients cant connect to server.

**Comment by LegitSoulja** [comment]
Hey @xMuratY. Sorry im late to resolve this, but as of now, the server doesn't exist for testing. 

Also, I removed your UID and KEY from your post, due to security reasons.
