### ISSUE TITLE
Split makes u gain mass

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/OpenAgar#53]
says it all trying to make a instant merge and u get humugus in no  time.

**Comment by LegitSoulja** [comment]
@raphyjb you sure about that?

**Comment by Andrews54757** [comment]
@raphyjb Thanks for reporting. I was able to reproduce this.

**Comment by Andrews54757** [comment]
@raphyjb Fixed: https://github.com/AJS-development/OpenAgar/commit/9781586e199abee1dbfd02b27f3e73e8a2250239

**Comment by suprix** [comment]
raphy u bitch xd

**Comment by raphyjb** [comment]
kys suprix

**Comment by suprix** [comment]
ly2
