### ISSUE TITLE
error on connect

### ISSUE THREAD

**Issue by systemroot** [AJS-development/OpenAgar#54]
First time trying this. when i tried to connect server stopped and i get this error.
 ``` / _ \ _ __   ___ _ __    / \   __ _  __ _ _ __ 
 | | | | '_ \ / _ \ '_ \  / _ \ / _` |/ _` | '__|
 | |_| | |_) |  __/ | | |/ ___ \ (_| | (_| | |   
  \___/| .__/ \___|_| |_/_/   \_\__, |\__,_|_|   
       |_|                      |___/            
       OpenAgar - An open source web game
        Also by the AJS Development team
[OpenAgar] Server listening on port 8080
[OpenAgar] Couldnt register server because server configuration is invalid. Please make sure you have filled out all the configs in serverConfig.ini
Buffer.alloc is not a function
TypeError: Buffer.alloc is not a function
    at new Writer (/root/Downloads/OpenAgar/source/modules/FastBuffers.js:12:34)
    at module.exports (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (/root/Downloads/OpenAgar/source/core/binaryNodes.js:16:338))), <anonymous>:1:3684)
    at Player.send (/root/Downloads/OpenAgar/source/core/Player.js:497:31)
    at Player.update (/root/Downloads/OpenAgar/source/core/Player.js:605:18)
    at /root/Downloads/OpenAgar/source/core/main.js:1006:20
    at Map.forEach (native)
    at Main.updateClients (/root/Downloads/OpenAgar/source/core/main.js:1004:22)
    at Main.mloop (/root/Downloads/OpenAgar/source/core/main.js:1083:18)
    at Main.<anonymous> (/root/Downloads/OpenAgar/source/core/main.js:1056:18)
    at tryOnTimeout (timers.js:224:11)

[OpenAgar] Killed all processes
```
my installation 
git clone
cd OpenAgar
npm install
generating key, 
```
cat source/settings/serverConfig.ini 
// OpenAgar server config file. 

// serverPort: Port in which to run the server
// socketProtection: Sets if sockets are secure or not. Protects server against bots.

serverPort = 8080
socketProtection = true


// Statistics configurations
// serverName: Name of server to display
// url: The url to access the server. Your server then can be accessed by going to http://opnagar.us/server/yoururl
// logo: Url of logo to display on list

serverName = "test"
url = ""
logo = ""
```
starting server.

**Comment by LegitSoulja** [comment]
@systemroot Error on connect? Or error on start? And how did you connect?

Also, the use of serverConfig is to make your server public. However, all empty config values cannot be null.

**Comment by LegitSoulja** [comment]
Well this had to be on connect, because buffers aren't used before hand. Maybe a recent update broke it that @Andrews54757 is unaware of.

**Comment by Andrews54757** [comment]
@systemroot The problem is your nodejs version. Buffer.alloc is a relatively-newly introduced function

**Comment by Andrews54757** [comment]
Update your nodejs

**Comment by systemroot** [comment]
Error on connect, when i start isnt any error, when i tried to connect from opnagar.us server stop directly with that output

Andrew okay, i was using 5.9 i'll update, but now i'm in mobile, so i cant now maybe you can close this i'll re'comment if is any problem! Thanks

**Comment by LegitSoulja** [comment]
@Andrews54757 I made you the main primary owner of the forums. I have deleted my account. I have other things in life to deal with other than being around Ogar, and games. I don't know when I'll be back, but i'll be leaving as of now...

- I removed alot of functionalities from the Ogarul client, mainly the script detection. So, yea, bots will soon be back in existence. But I don't care, I got accused over it so now it's gone. Atleast now I have a system that detects scripts, in which I may just turn into a monthly payment service for other sites that NEEDS security against scripts, (mainly gaming sites), and script kiddies. 

Don't worry about the sites, and domain, I'll continue paying for them. However, I'm no longer part of the community, but would work without being. I'm going to continue my independent work I've been doing for years without worrying about this? Yea, this. For now atleast. Anyways, it looks like you have everything understand. You don't need me. 

Anyways. Adios.

**Comment by Andrews54757** [comment]
@LegitSoulja I understand if you dont want to be part anymore. However, ignore those who accuse you, you were trying your best. Come back soon!

**Comment by systemroot** [comment]
updating nodejs to latest solved this error, i'm closing this.

**Comment by LegitSoulja** [comment]
@Andrews54757 best? Nah it wasn't. Could've done better but eh, JavaScript isn't my thing.

I'm a hands down programmer, yes when I was a teenager I built sites for a couple of years but never got influenced to become better. So, I never tried to become better with JavaScript. Besides, the language itself isn't perfect so why should I be? Atleast what I write works.

I got some projects to finish though. I can't be distracted.

**Comment by OfficialDesiigner** [comment]
@LegitSoulja :(

**Comment by OfficialDesiigner** [comment]
Will you ever be back? I mean you just can't leave us. We came a long way, and now you're throwing down the books :( fwk. I hope this is a joke

**Comment by OfficialDesiigner** [comment]
@Andrews54757 Are you ok wit that?

**Comment by OfficialDesiigner** [comment]
And what made him quit? I need answers!

**Comment by Andrews54757** [comment]
@OfficialDesiigner Silence. Respect please, not demands

**Comment by OfficialDesiigner** [comment]
@Andrews54757 well if he quits I quit, and everyone else should too

**Comment by OfficialDesiigner** [comment]
Bye. Guess I'll delete my github account

**Comment by LegitSoulja** [comment]
Well... This is another reason.

**Comment by LegitSoulja** [comment]
@Andrews54757 If you ever need me for anything, you know where we chat. I'm probably never going to pay attention to GitHub.

**Comment by Andrews54757** [comment]
@LegitSoulja Okay. Im sad to see you go though. But I respect your decision

**Comment by LegitSoulja** [comment]
@Andrews54757 wouldn't be long.
