### ISSUE TITLE
Invalid Key

### ISSUE THREAD

**Issue by omidh28** [AJS-development/OpenAgar#6]
I followed instruction in README but even though my key.txt is exactly what the game gave me, I'm still receiving error about invalid key.

BTW, Why parseInt the key? https://github.com/AJS-development/OpenAgar/blob/master/source/core/controller.js#L27

**Comment by Andrews54757** [comment]
Quoting @LegitSoulja 

> When the bell rings

**Comment by Andrews54757** [comment]
#4

**Comment by darknight99x** [comment]
@omidh28 add me on Skype @ Darknight99x 
I want to speak to you about a project I have. I think you're capable,
thanks.

**Comment by Andrews54757** [comment]
Hello, I dont do skype. Instead, mail me at (mygithub username)@gmail.com

**Comment by darknight99x** [comment]
@Andrews54757 Will this project self update as of now or will we have to get new IDs?

**Comment by Andrews54757** [comment]
If you want to update the project, then just download it again, and move the key.txt file from the old one to the new one. You can then delete the old one.

**Comment by LegitSoulja** [comment]
Just download and overwrite the old content.
