### ISSUE TITLE
How to play? openAgar

### ISSUE THREAD

**Issue by DeadLord1337** [AJS-development/OpenAgar#60]
How? Not bat file.. Start.bat

**Comment by FantasyIsBae** [comment]
This is how to play ...

1. Learn basic NodeJS 
2. Learn how to use command prompt

**Comment by Andrews54757** [comment]
@DeadLord1337 , you have disobeyed the rules. Real issues only


OFFENSE:
> Disobeying of the issues section rules


Today I hereby declare you BANNED from AJS
> Banned on February 12 2017
