### ISSUE TITLE
more then 100 users?

### ISSUE THREAD

**Issue by raphyjb** [AJS-development/OpenAgar#62]
I was in the first 100 users, and cannot log in for odd reason says its full...

**Comment by LegitSoulja** [comment]
@raphyjb I did a full site revamp a few days ago. Can you provide an image of the error message? Thanks.

**Comment by segg21** [comment]
Also I am closing this issue because this is website related, not server/client related to OpenAgar. All website related issues can be reported via my email for a faster response at support@legitsoulja.info.

**Comment by segg21** [comment]
I found, and fixed the issue, it was a minor bug that caused the cap to be unrecognized.
