### ISSUE TITLE
Console problems

### ISSUE THREAD

**Issue by YouCanNotKnow** [AJS-development/OpenAgar#63]
Hello. I followed all the instructions and have created the server but im having some issues. I run index.js and the server thing pops up (http://prntscr.com/ejggj6) and then i go onto opnagar.us. It loads in and everything looks fine but when i press play it disconnects me and an error message pops up (http://prntscr.com/ejgh2h). I dont know what is happening but it would be useful to have a response.

**Comment by FantasyIsBae** [comment]
> Hello. I followed all the instructions and have created the server but im having some issues. I run index.js and the server thing pops up (http://prntscr.com/ejggj6)

This isn't an error , just make sure you have filled in all the options in the configuration files:) 
 
>And then i go onto opnagar.us. It loads in and everything looks fine but when i press play it disconnects me and an error message pops up (http://prntscr.com/ejgh2h).

Looks like "Buffer" hasn't been defined @Andrews54757 
```
writer: class Writer {
        constructor(size) {
            this.index = 0;
         this.buffer = (here ===>) Buffer.alloc(size); 
        }
```

**Comment by LegitSoulja** [comment]
@YouCanNotKnow please update node.

**Comment by LegitSoulja** [comment]
https://github.com/AJS-development/OpenAgar/issues/54 Duplicate.

**Comment by YouCanNotKnow** [comment]
duplicate?

**Comment by Andrews54757** [comment]
buffer.alloc is a new nodejs feature

**Comment by FantasyIsBae** [comment]
@YouCanNotKnow Update your [Node.js](https://nodejs.org/en/)
