### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by gyeyoqu** [AJS-development/OpenAgar#64]
Why not focus on something like Ogar? , In making an agar with the same improved characteristics? , Because they work in OpenAgar, being so good programmers and that no one takes importance to your project? , I recommend something more like agar.io

**Comment by gyeyoqu** [comment]
an example:
Many agar servers already exist, for example no one makes clients

**Comment by LegitSoulja** [comment]
@gyeyopu 

I barely understood a word you said. Do you have a clue to what you're talking about? Asking? Or wanting?

... Buffering language

There's many reasons why we aren't recommending the things you're saying.

We moved away from being part of agario, and Ogar. This is nothing alike those 2.

If you want an Ogar, Agario type server you're in the wrong place, complaining about the wrong thing. 

Overall, OpenAgar is better than Ogar (Server), with more efficiency. Faster, light weight and smarter.

OpenAgar is our own thing. Our own server, client, and implementations. 

You aren't even a registered key holder of OpenAgar. How can you even compare? Or demand a change of something?
