### ISSUE TITLE
Client Engine

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/OpenAgar#67]
I've discovered more for an engine that'll work for OpenAgar, however there's major pros and cons, and file size differentials.

Shall we go advanced? Try to blow out the graphics and physics?

Or something flat, basic, lightweight?

I was going more of a webgl, http://www.pixijs.com

Something lightweight/simple, http://lib.ivank.net/?p=documentation

And I've heard [iioengine](http://iioengine.iioinc.com/) was good aswell.

I don't know. What should we use?

**Comment by SharkFinPro** [comment]
@LegitSoulja Do both, And add an option to switch :D

**Comment by FantasyIsBae** [comment]
@LegitSoulja Not every browser supports WebGl (As far as I know)
@SharkFinPro And an option to switch might not be memory efficient (But i might be wrong)

**Comment by SharkFinPro** [comment]
@FantasyIsBae 2 different client pages, still mem efficient

**Comment by LegitSoulja** [comment]
@SharkFinPro your statement wasn't the smartest. Why create 2 clients?

@FantasyIsBae most of this world can run webgl, but there's a canvas fallback for the browsers that isn't supported.

I provided links, I suggest discover before shouting. Actually looking for Andrews response.

**Comment by LegitSoulja** [comment]
I was looking at iioengine, amd kind-of got attached to their library. PixiJS is very confusing to understand during these stages, v4 especially, and there's old docs and etc. No docs for client side usage.

iioengine got some nice things that I see that can be used with OpenAgar http://iio.js.org/#api/quad

**Comment by LegitSoulja** [comment]
@Andrews54757 I got an idea aswell, check gitter.

**Comment by LegitSoulja** [comment]
nvm @Andrews54757 about gitter

**Comment by Andrews54757** [comment]
@LegitSoulja You pick. However, if you want me to make it, I think I could make one in a month of hard work.

**Comment by LegitSoulja** [comment]
@Andrews54757 Well, I mean I been started it officially last month. But i just don't know what'll be the best engine to use since some people recommended me something different.

If we build webgl, then pixijs. However, just something simple and basic i'll use iioengine. 

I think webgl will be nice, But I really don't know exactly how it'll turn out to be.

**Comment by SharkFinPro** [comment]
@LegitSoulja Does it draw the entire map, or only what your computer displays

**Comment by LegitSoulja** [comment]
@SharkFinPro ? Does? It does nothing. It's how you do/program it, and idk you tell me. 

Doesn't take a rocket scientist to pick an efficient solution.

**Comment by SharkFinPro** [comment]
ok
