### ISSUE TITLE
how could I open port

### ISSUE THREAD

**Issue by Faris90** [AJS-development/OpenAgar#69]
It says port is closed

**Comment by LegitSoulja** [comment]
Then your port is closed. Default port is 8080.

**Comment by Faris90** [comment]
the port was 8080

**Comment by LegitSoulja** [comment]
@Faris90 Btw, our site is now accessible, (Server list, forums)

http://home.opnagar.us

**Comment by SharkFinPro** [comment]
@Faris90 
Port forward

**Comment by LegitSoulja** [comment]
@Faris90 Check and make sure your port is open > http://canyouseeme.org/

If it is, I can assist further, if not, I cannot help with port forwarding.

**Comment by LegitSoulja** [comment]
@SharkFinPro and hola, didn't expect you to be on.

**Comment by SharkFinPro** [comment]
@LegitSoulja :P
just working on my diep....i seriously need help xD

**Comment by SharkFinPro** [comment]
@LegitSoulja how do i combine everything together?... :P

**Comment by LegitSoulja** [comment]
@SharkFinPro requirejs?

**Comment by SharkFinPro** [comment]
whats requirejs
require()?

**Comment by FantasyIsBae** [comment]
@SharkFinPro [Here](http://requirejs.org/)

**Comment by LegitSoulja** [comment]
@SharkFinPro If you want to combine things together, then combine it the best way you can.
