### ISSUE TITLE
Key Request

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/OpenAgar#7]
Hi, interested in development of OpenAgar. Thanks.

**Comment by Andrews54757** [comment]
Need id for key

**Comment by darknight99x** [comment]
ID: zXH3vhz81Iy3SKaps3O9

**Comment by Andrews54757** [comment]
115511078670. I also replied to your post in reddit

**Comment by darknight99x** [comment]
I saw, thanks for the detailed feedback.

**Comment by Andrews54757** [comment]
Dumb GitHub turning `115511078670`
 into
 115511078670.

**Comment by darknight99x** [comment]
Okay thanks, i'll be fiddling around and let you know if I find anything strange.

**Comment by darknight99x** [comment]
@Andrews54757 

Upon server restart I got this:
`Invalid key!, make sure you have the right key! Your id is: false`

**Comment by Andrews54757** [comment]
What machine is your server running on?

**Comment by darknight99x** [comment]
Win 10 x64 10240

**Comment by Andrews54757** [comment]
Perhaps your mac address changed. Please run this nodejs script twice and report the results
[t.js.zip](https://github.com/AJS-development/OpenAgar/files/587558/t.js.zip)

**Comment by Andrews54757** [comment]
Do exactly the same thing you did from before when you got it to work and re run the script I gave you afterwords

**Comment by darknight99x** [comment]
`C:\Users\Darknight99x\Desktop\a\source\core\controller.js:37
 throw e
 ^
Invalid key!, make sure you have the right key! Your id is: false

C:\Users\Darknight99x\Desktop\a>cd ..

C:\Users\Darknight99x\Desktop>cd temp

C:\Users\Darknight99x\Desktop\temp>node t.js
AMD FX(tm)-6100 Six-Core Processor
9c:b7:0d:3f:e6:86
win32
x64
Windows_NT`

**Comment by Andrews54757** [comment]
And the second set of data ... (do exactly the same thing you did before that broke OpenAgar, then run it)

**Comment by darknight99x** [comment]
Do you want me to reset OpenAgar? Because I can't reproduce what happened because my ID is gone.

**Comment by Andrews54757** [comment]
Just run the script again

**Comment by Andrews54757** [comment]
Il try to reproduce using my vms

**Comment by darknight99x** [comment]
'C:\Users\Darknight99x\Desktop\temp>node t.js
AMD FX(tm)-6100 Six-Core Processor
9c:b7:0d:3f:e6:86
win32
x64
Windows_NT

C:\Users\Darknight99x\Desktop\temp>node t.js
AMD FX(tm)-6100 Six-Core Processor
9c:b7:0d:3f:e6:86
win32
x64
Windows_NT

C:\Users\Darknight99x\Desktop\temp>'
Okay I ran it twice.

**Comment by Andrews54757** [comment]
Strange

**Comment by darknight99x** [comment]
`throw e
 ^`

Is it looping code after successful key? Is what it looks like.

**Comment by Andrews54757** [comment]
It works for all the virtual machines I have. Im gonna test more though. But currently, delete a file called `backup` in the open agar dir and delete a file called `mcuid` to reset your id

**Comment by darknight99x** [comment]
Done. New ID is: G2W9Fjk4tEtexIMRQQ2l

**Comment by Andrews54757** [comment]
932665533761

**Comment by Andrews54757** [comment]
I don't think it will happen again though

**Comment by Andrews54757** [comment]
Wait, did you ever run project N, that could be the problem

**Comment by darknight99x** [comment]
I figured out the issue. 

```
Changing the folder path name where OpenAgar is at causes the fault.

C:\Users\Darknight99x\Desktop\>rename a b

C:\Users\Darknight99x\Desktop\b>node index.js

C:\Users\Darknight99x\Desktop\b\source\core\controller.js:37
 throw e
 ^
Invalid key!, make sure you have the right key! Your id is: false
```

**Comment by Andrews54757** [comment]
I wonder why

**Comment by darknight99x** [comment]
I changed the directory name back to previous and it's now working.

**Comment by Andrews54757** [comment]
Oh, I know why, its a protection system I added a while ago for the ``backup`` file. If you change the dir, delete the backup file. I don't need the protection system anymore, yet didn't remove it because I was lazy. Im gonna remove it
