### ISSUE TITLE
default port is not working

### ISSUE THREAD

**Issue by Faris90** [AJS-development/OpenAgar#70]
Before posting your issue, please take a look at these things

1. Do not ask how to run, we will not help you but will ban you. Read the readme carefully.
2. Search up your issue first on github, you might find your answer. Duplicate issues = soft ban (1 week)
3. Always be concise. Think of your words
4. Must be real issues, which means it has to be code issues. Or, you can face another ban
5. A title isnt enough, a description is needed, violators will definatly be banned
6. Must include the error, and the file in which it occurs. Otherwise, your issue will be closed immediatly
7. Please keep OpenAgar's issues just for OpenAgar. Other projects like ogar, ogarul, multiogar, cigar, and etc is not supported here.
8. Please do not put issues asking us to put Agar.io physics on OpenAgar. Like we said, OpenAgar is not Agar.io, and is different. Similar, but different
9. No profanity whatsoever. Doing so will be very very bad for you.
10. Post things that violate rule 1,3,4,5,6, and/or 7 here: http://forum.ogarul.io

**Comment by LegitSoulja** [comment]
@Faris90 would you like to fix your issue? Just a warning, as the owner doesn't tolerate spam, or issues that doesn't have much information. Default port is not working ..? NEI (Not Enough Information). Please read the guidelines.

**Comment by SharkFinPro** [comment]
First, You just broke rule #5. What do you mean by "default port is not working"?
This can mean many things, and we can not help you troubleshoot until you give us more info.
Please edit this now or risk getting banned from making future requests for help.
Thanks


@LegitSoulja @Andrews54757

**Comment by SharkFinPro** [comment]
@LegitSoulja oops my internet lagged, my message took a while to send =/

**Comment by LegitSoulja** [comment]
@SharkFinPro first come, first serve :)

**Comment by Andrews54757** [comment]
@Faris90 Is now banned


OFFENSE:
> ^^^


Today I hereby declare you BANNED from AJS Indefinitely
