### ISSUE TITLE
hello andrewy

### ISSUE THREAD

**Issue by AlexHGaming** [AJS-development/OpenAgar#72]
how to host omg i asked it now im banned oh fuck well dont mind me lemme grab my stuff and leave

**Comment by LegitSoulja** [comment]
@AleHGaming Actually, you're being banned for spam, and being an immature little prick. 

I let what happened slide earlier, but now you're acting like a 2 year old who just got computer access and don't know what they are doing.

Bad literature aswell, stay in school? Best bet for yourself. 

Bye kiddo.

**Comment by LegitSoulja** [comment]
@AlexHGamimg

**Comment by AlexHGaming** [comment]
at least learn how to spell my name right

**Comment by LegitSoulja** [comment]
That name I could care less about.
