### ISSUE TITLE
Help session #1

### ISSUE THREAD

**Issue by curse911** [AJS-development/OpenAgar#78]
How do I run OpenAgar? How do I use stats?

**Comment by Andrews54757** [comment]
WINDOWS:

1. Make sure to have nodejs installed. (https://nodejs.org)
2. Open command prompt  (search it up on windows)
3. Download a copy of OpenAgar onto your desktop
4. Write `cd ` into the command prompt and drag the OpenAgar folder into it
5. Run `node index.js`
6. Register the server through http://login.opnagar.us
7. Re-run the server using `node index.js` (do cmd-c to exit)
8. Edit configurations using a text editor - Configs are in source/settings

**Comment by curse911** [comment]
thank u man but do u have a vid or pics cuz i have bad eng and sry for bothering u

**Comment by Andrews54757** [comment]
@curse911 I created a start.bat file for you. Redownload and it will be inside the folder

**Comment by curse911** [comment]
ty

**Comment by curse911** [comment]
so now what do i have to do ?

**Comment by Andrews54757** [comment]
Did it run?

**Comment by SharkFinPro** [comment]
Andrew im having problems logging into the site bc im part of ajs on github

**Comment by Andrews54757** [comment]
I know. What problems. Screenshot

**Comment by curse911** [comment]
yess thank u

**Comment by Andrews54757** [comment]
@curse911 Did you registrate the server?

**Comment by SharkFinPro** [comment]
![ooof](https://user-images.githubusercontent.com/18649707/28759674-eb4a1e3a-7554-11e7-8273-281d078c5eeb.PNG)

**Comment by SharkFinPro** [comment]
i cant login =/

**Comment by Andrews54757** [comment]
@SharkFinPro Just press the green button

**Comment by SharkFinPro** [comment]
which

**Comment by SharkFinPro** [comment]
authorize ajs dev?

**Comment by Andrews54757** [comment]
The authorize button

**Comment by SharkFinPro** [comment]
that needs a password

**Comment by Andrews54757** [comment]
Your password

**Comment by SharkFinPro** [comment]
ok

**Comment by SharkFinPro** [comment]
ah that works :P

**Comment by SharkFinPro** [comment]
btw can i change start.bat?

**Comment by Andrews54757** [comment]
yea

**Comment by SharkFinPro** [comment]
k

**Comment by SharkFinPro** [comment]
done

**Comment by curse911** [comment]
no how do i registrate the server ?

btw there is a bug that i cant move and my cell is at top left corner

**Comment by Andrews54757** [comment]
@curse911 There is an id given to you on startup. Go to login.opnagar.us, login using your github, and go to registration.

**Comment by curse911** [comment]
@Andrews54757 sry man but there is a error saying that it couldnt register because serv confg is invalid

**Comment by Andrews54757** [comment]
@curse911 Edit source/settings/serverConfig.ini.

**Comment by Andrews54757** [comment]
At the bottom, fill out the configs

**Comment by curse911** [comment]
i filled it now there is another error saying serv port isnt open

**Comment by Andrews54757** [comment]
@curse911 You must port foward

**Comment by SharkFinPro** [comment]
@curse911 Port forward - search it up, has somethign to do with ur router

**Comment by curse911** [comment]
port forward ? 

btw i am using my iphone lol

**Comment by Andrews54757** [comment]
@curse911 Go to http://192.169.1.1

**Comment by curse911** [comment]
ok

**Comment by SharkFinPro** [comment]
yo andrew
how do you make an openagar plugin?

**Comment by curse911** [comment]
it says that i cant open it

**Comment by SharkFinPro** [comment]
@curse911 are you at your house?

**Comment by curse911** [comment]
and its suggest me this ‪http://192.169.1.1.ipaddress.com

**Comment by curse911** [comment]
@SharkFinPro no

**Comment by curse911** [comment]
i am at my grandma house

**Comment by Andrews54757** [comment]
@curse911 wrong address, do http://192.168.1.1

**Comment by LegitSoulja** [comment]
@SharkFinPro 

Compiler https://github.com/AJS-development/OAPluginCompiler

And check the wiki

**Comment by LegitSoulja** [comment]
@curse911 if you're not doing this on your own network, we don't acknowledge you proceeding further. The downfall is you not being able to setup your router ports correctly, and not being able to login.

We do not provide additional support for that. Sorry.

**Comment by Andrews54757** [comment]
@LegitSoulja We do have this tool...

**Comment by Andrews54757** [comment]
@SharkFinPro Finished the smooth mech

**Comment by Andrews54757** [comment]
@LegitSoulja That wasnt it

**Comment by LegitSoulja** [comment]
@Andrews54757 you forcing it? I thought it can be ignored..

**Comment by Andrews54757** [comment]
@LegitSoulja He didnt fill out serverconfig.ini

**Comment by Andrews54757** [comment]
@LegitSoulja He wanted to post his server

**Comment by Andrews54757** [comment]
@curse911 If you dont want to make your server public, then you can ignore stats

**Comment by LegitSoulja** [comment]
@Andrews54757 but now, im letting him know that he locally, if the config was back default. That warning about an invalid config would not "Terminate" the server, therefor can be ignored.

**Comment by curse911** [comment]
i just want to play on my own private server .
btw is there any commands exe: kill all - mass - minion ?

**Comment by Andrews54757** [comment]
@curse911 Do `plugin install EssentialCommands` inside of openagar

**Comment by Andrews54757** [comment]
@curse911 Minions are `plugin install Minions`

**Comment by curse911** [comment]
how ?
and is there a macro ?

**Comment by Andrews54757** [comment]
@curse911 Start openagar, and do `plugin install EssentialCommand`

**Comment by Andrews54757** [comment]
@curse911 No, there is no macro yet. Will be soon

**Comment by curse911** [comment]
i did it but it says it can not be found

**Comment by LegitSoulja** [comment]
```EssentialCommands```

**Comment by Andrews54757** [comment]
@curse911 Whenever you want to look up a plugin, you can also do:

`plugin search {search term}`

**Comment by curse911** [comment]
i typed plugin search minion and it dosnt work

**Comment by LegitSoulja** [comment]
@curse911 Yea, You can to respect plugin names. Case sensitive
```Minions```

**Comment by curse911** [comment]
i typed minions and it didnt work too

**Comment by curse911** [comment]
nvm it worked thank u

**Comment by SharkFinPro** [comment]
@LegitSoulja Thx :D 
@Andrews54757 Yay! Good job!

**Comment by Andrews54757** [comment]
@SharkFinPro A secret:

Do `stats()` in console. (javascript console, chrome dev tools)

**Comment by SharkFinPro** [comment]
it returns undefined @Andrews54757

**Comment by LegitSoulja** [comment]
@SharkFinPro it's visually drawn on canvas.

**Comment by fayizan** [comment]
Cell shake is hard when the cell is small and Skin and Name get blurry after growing big 

![screenshot_79](https://user-images.githubusercontent.com/19163419/28766193-07171266-75ec-11e7-865c-ea956f565289.png)

**Comment by Andrews54757** [comment]
What is cell shake. Also, skin and name graphics are made like that for performance. You probably noticed its the least cpu intensive client available

**Comment by fayizan** [comment]
@Andrews54757 its not looking pleasant with blur( how about giving it like an option ) and lemme record the cell shake : |

**Comment by AztroAgario** [comment]
when i open the start.bat it installs the dependencies and after that it gives me this error: Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'. 

HELP ME PLEASE

**Comment by fayizan** [comment]
@LegitSoulja 

![screenshot_82](https://user-images.githubusercontent.com/19163419/28812075-87e1257a-76b0-11e7-95df-39c36eb7cd17.png)

**Comment by fayizan** [comment]
@Andrews54757  https://youtu.be/hIENOqCBQAw

**Comment by Andrews54757** [comment]
@fayizan I dont know why this happens

**Comment by Cabotrez** [comment]
ok
