### ISSUE TITLE
read description

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/OpenAgar#79]
i see the client has just gone up...for my server, should i download latest release
https://github.com/AJS-development/OpenAgar/releases
or downlaod the current code directly as a zip
or are you going to make an new release soon?

**Comment by SharkFinPro** [comment]
nvm just saw the how to start server
_stupid me_

**Comment by LegitSoulja** [comment]
@SharkFinPro haha that release was released on Jan 20. Yea, go for it!.
