### ISSUE TITLE
Client Draw Error

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/OpenAgar#8]
Issue with the client, the server restarted, the blobs remain drawn, but they don't exist internally on the server. You can hover over them and the blobs just move around when you're on them. Weird. (Not really a massive issue, since a simple reload fixes the issue.)

One big I noticed from these older clients is that; **the cells (in the code) once killed off are still in memory, just turned invisible, that is one of the biggest laggers on this client.**
This client is that old code from the beta versions of agar.io
This client really needs to be re-written from scratch or re-done.

![untitled](https://cloud.githubusercontent.com/assets/19356956/20243413/43017c0c-a924-11e6-9d4e-ff3dba68e5eb.png)

**Comment by Andrews54757** [comment]
If a server restarts, then you should reload the client. The current client is for development purposes. The final client will be something like this: 

![screen shot 2016-11-12 at 10 19 13 pm](https://cloud.githubusercontent.com/assets/13282284/20243463/22efd722-a926-11e6-94e9-1e99ec18fcbb.png)

Its the new client we've been working on

**Comment by Andrews54757** [comment]
Looks cool huh? And thats just half of it

**Comment by darknight99x** [comment]
Do you plan on releasing a free source client as well?

**Comment by Andrews54757** [comment]
No. This is what pains me the most. I wanted to release them, I really do. But looking back at OgarUL, where I did. It became nasty. Bad people use the things I put out for bad intentions. I will release the socket apis for people to create their own. Note that in order to use your own, the server must have secure connections off in the configurations (serverService.js). The outdated apis are here: https://github.com/AJS-development/Project-Nehemiah/issues/7

**Comment by Andrews54757** [comment]
There are multiple changes in the protocol now though. This is due to the slow FPS protocol being implemented as well as the ditching of RSON

**Comment by darknight99x** [comment]
Shame. The only free source client out there I refuse to use, it's quite garbage. And I don't have time to make my own anymore.

**Comment by Andrews54757** [comment]
Another change is that custom url skins won't work. So bye by ``|url|name``. Custom server skins will still work, the skins that the owner of the server created. This is mainly because people were using inappropriate skins. (like porn and stuff)

**Comment by Andrews54757** [comment]
Basically, I'm not going to give away stuff willy nilly because of the way people misuse them. If only people didn't ruin things for others.

**Comment by darknight99x** [comment]
Are you looking for someone who can help guide educated players toward this project, 
or be someone that can help people out? I can fill that position in. I'd love to help in anyway I can.

**Comment by Andrews54757** [comment]
Support for this project is very limited. This is also because of the way people misused the issues section of the repo. In OgarUL, it got too bad. About 95% of issues weren't real ones. They were like "how do i do this" or "lets chat here" or random things like "Willy wonka's death". It wasted our time too much. We barely spend our time programming and was wasting time on kiddies. Here, if you make one screw up, you get banned permanently

**Comment by darknight99x** [comment]
Well that's what I meant, I noticed how cancerous the foreign users that were coming in, spamming useless issues, when there were people who ACTUALLY needed the help that I so desperately wanted to do.

I could be your issue guy, maybe helping the **REAL** users and taking care of the "trolls and spammers".

**Comment by Andrews54757** [comment]
It would be too much for you. It was too much even for the both of us. So now, we just don't deal with it

**Comment by Andrews54757** [comment]
But, you can be a developer, not a support guy if you want

**Comment by darknight99x** [comment]
Well I wouldn't mind giving me a shot, my job is an Amazon Support Representative, I take strange and diluted calls all of the time, I am on all of the time willing to deal with it.

I am okay though if you decline, I just really want to help people, I love doing so.

**Comment by Andrews54757** [comment]
Me too. Thats the reason for the creation of AJS development. To help people. But be warned that the people here can be very very rude

**Comment by darknight99x** [comment]
I understand. I have seen the people here before, and people on Amazon are notorious for being buttholes. :P

**Comment by Andrews54757** [comment]
So, okay, you can help with support. But also note that most support has moved on to https://forum.ogarul.io in order to let us be focused.

**Comment by darknight99x** [comment]
Okay, how should I deal with support on the forums? Can you add me on a more easier message service? Skype, or?

**Comment by darknight99x** [comment]
Well let me know how you want to approach this, maybe access to close and open issues, or we can discuss more on Skype, add me @ Darknight99x

**Comment by Andrews54757** [comment]
Wait, looking through all logs

**Comment by Andrews54757** [comment]
Im sorry, but you cannot be a support guy. I just looked through all the logs and records, and found out that we already have a person.

**Comment by darknight99x** [comment]
Okay that's fine. Thanks anyways. :)

**Comment by Andrews54757** [comment]
Okey dokey

**Comment by LegitSoulja** [comment]
No, that's not the client lol.

**Comment by LegitSoulja** [comment]
i keep forgetting to remove it from the main site. I've been working on something better, after unity fails.

**Comment by darknight99x** [comment]
Ah okay well, you're working on something better so that's awesome.
