### ISSUE TITLE
Installation - Mac

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/OpenAgar#80]
### Make sure to install nodejs (http://nodejs.org)

<img width="1280" alt="screen shot 2017-07-30 at 10 40 30 pm" src="https://user-images.githubusercontent.com/13282284/28760844-3baddb3c-7578-11e7-9602-0af874c66856.png">

### Download the latest copy of OpenAgar

<img width="1280" alt="screen shot 2017-07-30 at 10 42 57 pm" src="https://user-images.githubusercontent.com/13282284/28760868-811b94ca-7578-11e7-81d9-3321fe620aea.png">

### Copy to desktop and open terminal

<img width="1280" alt="screen shot 2017-07-30 at 10 44 23 pm" src="https://user-images.githubusercontent.com/13282284/28760886-a7d3a756-7578-11e7-8db5-35bf858af446.png">

### Type `cd ` and then drag-n-drop the folder to it. Then press enter

<img width="1280" alt="screen shot 2017-07-30 at 10 45 36 pm" src="https://user-images.githubusercontent.com/13282284/28760909-d772ddc4-7578-11e7-8be8-d929f4efc06d.png">

### Do `node index.js`. Copy the id given to you

<img width="682" alt="screen shot 2017-07-30 at 10 47 09 pm" src="https://user-images.githubusercontent.com/13282284/28760938-0ff8d45a-7579-11e7-84fc-768def09b768.png">

### Type `stop` or do cmd-c to exit. Then go to http://login.opnagar.us. Login with github.

<img width="1280" alt="screen shot 2017-07-30 at 10 49 26 pm" src="https://user-images.githubusercontent.com/13282284/28760983-5c0eaaf4-7579-11e7-9a16-2070b433e4d2.png">

### Go to the registration page, and paste your server id.

![screen shot 2017-07-30 at 10 50 51 pm](https://user-images.githubusercontent.com/13282284/28761006-8d9db59c-7579-11e7-94ef-faee3f49d0cd.png)

### Press register and restart the server (`node index.js`). And your done! To play, go to http://opnagar.us. (chrome or firefox is recommended)

![screen shot 2017-07-30 at 11 18 53 pm](https://user-images.githubusercontent.com/13282284/28761566-7b17ff78-757d-11e7-9ac1-22178c65d8d8.png)

**Comment by Mistik** [comment]
Hi!

I cant register my ID as the website is down

**Comment by Andrews54757** [comment]
Project has been closed.

**Comment by Mistik** [comment]
> Project has been closed.

Are you available for freelance work?

Add my discord 〖ƝƁƘ〗✧Ṃ!ṨҬ!Ḱ✧#4182
