### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by AztroAgario** [AJS-development/OpenAgar#81]
When i launch my start.bat it installs the dependencies and then gives me this error : Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

What should i do?

**Comment by Andrews54757** [comment]
@AztroAgario What operating system

**Comment by LegitSoulja** [comment]
@AztroAgario @Andrews54757

This looks to be a common issue. He needs to update nodejs.

**Comment by Andrews54757** [comment]
nope. He need to upgrade his os

**Comment by Andrews54757** [comment]
Hes missing the c++ compiler on his computer

**Comment by LegitSoulja** [comment]
@Andrews54757 if it windows, doesn't make sense.

https://github.com/uNetworking/uWebSockets/issues/315

**Comment by LegitSoulja** [comment]
@Andrews54757 node, and npm wouldn't work in that case. I don't think he'll be able to install if he didn't have gcc

**Comment by Andrews54757** [comment]
@LegitSoulja He needs to update it

**Comment by Andrews54757** [comment]
@LegitSoulja Gitter pls

**Comment by LegitSoulja** [comment]
@Andrews54757 he should try installaling VisualStudios, or any missing Redistributibles. An OS update overall possibly. https://github.com/felixrieseberg/windows-build-tools

**Comment by AztroAgario** [comment]
my os is Win 10 and i believe its becuz of the activation. when i got my laptop its windows wasnt activated. is that the case?

**Comment by Andrews54757** [comment]
mabye, or mabye not

**Comment by Andrews54757** [comment]
@AztroAgario Do `npm install -g node-gyp` and retry

**Comment by LegitSoulja** [comment]
@AztroAgario unactivated version of what windows? Pro?

**Comment by LegitSoulja** [comment]
And can you provide your node version? I'm curious. 
Search CMD,

Type in the console
```node -v```

**Comment by AztroAgario** [comment]
v8.2.1

**Comment by AztroAgario** [comment]
@Andrews54757 i did the thing you said "Do npm install -g node-gyp and retry". It still gives me the error

**Comment by seifgaming** [comment]
my windows 10 is activated and i have the same proplem

**Comment by LegitSoulja** [comment]
Try this. It shouldn't hurt.

- Delete node_modules 
- Delete ws or uws module (If global)
- Run ```no cache clean```
- Run OpenAgar (Don't do npm install).

**Comment by LegitSoulja** [comment]
3 very final options,
- Install any missing windows redistributions (https://www.microsoft.com/en-us/download/details.aspx?id=48145) 
- Get GCC (Mingw-w64)
- Install Visual Studios (Which includes all development tools).

After all. This issue is weird. Either there's some other ws breaking uws, or your computer went back in the past and forgot what language this era uses to compiles.

**Comment by seifgaming** [comment]
tried all what you said, what version of node.js you use @LegitSoulja 
so i could try i tried an old and  a new version no one work

**Comment by LegitSoulja** [comment]
@seifgaming give me like 10 minutes. I'll get to the bottom of this.

**Comment by LegitSoulja** [comment]
@seifgaming what previous and new version did you use?

**Comment by LegitSoulja** [comment]
I am going to update, and see if I can reproduce this issue.

**Comment by seifgaming** [comment]
@LegitSoulja 6.11.2 , 8.4.0

**Comment by LegitSoulja** [comment]
@seifgaming I am currently, or was using 7.7.1. But now I am updating.

**Comment by LegitSoulja** [comment]
@seifgaming ok yea. I updated to v8 and that error occurred.

```
C:\Users\LegitSoulja\Documents\OpenAgar\update>node index
Checking Modules
0 Modules need to be installed; 0 modules need to be updated
openssl config failed: error:02001003:system library:fopen:No such process
C:\Users\LegitSoulja\Documents\OpenAgar\update\node_modules\uws\uws.js:38
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (C:\Users\LegitSoulja\Documents\OpenAgar\update\node_modules\uws\uws.js:38:19)
    at Object.<anonymous> (C:\Users\LegitSoulja\Documents\OpenAgar\update\node_modules\uws\uws.js:42:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\LegitSoulja\Documents\OpenAgar\update\node_modules\simplesockets\index.js:37:13)
```

This is due to uws as seems, not being updated to support v8. I'll check more on that in a second.

**Comment by LegitSoulja** [comment]
@seifgaming @AztroAgario 

The solution to fix this issue is simple.

Inside of the node_modules folder with OpenAgar, the uws folder and delete it.

Once deleted, inside that folder you will run the command ```npm install uws```

Proceed to run the game afterwards...

**Comment by seifgaming** [comment]
i will try

**Comment by LegitSoulja** [comment]
@seifgaming I promise you. Issue solved.

**Comment by seifgaming** [comment]
doesnt work 
Checking Modules
0 Modules need to be installed; 0 modules need to be updated
C:\Users\seift\Desktop\OpenAgar-master\node_modules\uws\uws.js:38
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (C:\Users\seift\Desktop\OpenAgar-master\node_modules\uws\uws.js:38:19)
    at Object.<anonymous> (C:\Users\seift\Desktop\OpenAgar-master\node_modules\uws\uws.js:42:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\seift\Desktop\OpenAgar-master\node_modules\simplesockets\index.js:37:13)
Press any key to continue . . .

**Comment by LegitSoulja** [comment]
@seifgaming that's very strange in fact. I'll keep looking for a resolution.

However, With the instructions given, I was successfully able to fix by updating uws. 

I'm literally going to pass you the binary of uws to replace and use.

**Comment by LegitSoulja** [comment]
[uws.zip](https://github.com/AJS-development/OpenAgar/files/1272716/uws.zip)

Delete the uws folder in node_modules again, and put what's in the zip

**Comment by seifgaming** [comment]
ok

**Comment by seifgaming** [comment]
nope doesnt work

**Comment by LegitSoulja** [comment]
@seifgaming then you must have a 32bit pc?

**Comment by LegitSoulja** [comment]
```javascript
const native = (() => {
    try {
        try {
            return process.binding('uws_builtin');
        } catch (e) {
            return require(`./uws_${process.platform}_${process.versions.modules}`);
        }
    } catch (e) {
        const version = process.version.substring(1).split('.').map(function(n) {
            return parseInt(n);
        });
        const lessThanSixFour = version[0] < 6 || (version[0] === 6 && version[1] < 4);

        if (process.platform === 'win32' && lessThanSixFour) {
            throw new Error('µWebSockets requires Node.js 6.4.0 or greater on Windows.');
        } else {
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            'available for your system. Please install a supported C++11 compiler and reinstall the module \'uws\'.');
        }
    }
})();
```

**Comment by seifgaming** [comment]
mine is 32

**Comment by seifgaming** [comment]
where should i add this code?

**Comment by LegitSoulja** [comment]
Then it's more than likely impossible for you to run OpenAgar I'm afraid.

**Comment by LegitSoulja** [comment]
@seifgaming it's just for documentation, if you could read it and understand why you're getting that error.

**Comment by seifgaming** [comment]
ok im really happy for your help i will try to fix it hope it work

**Comment by LegitSoulja** [comment]
@seifgaming I'm afraid to say there's no further solution to your 32 bit issue.

**Comment by LegitSoulja** [comment]
@seifgaming You could possibly, 

- Downgrade NodeJS
- Downgrade uws

But I'm uncertain if win32 is still locked.

**Comment by seifgaming** [comment]
so all people 32 bit cant run or just my pc?

**Comment by LegitSoulja** [comment]
I can't say. I'm not a computer scientist but however I am still researching.

**Comment by seifgaming** [comment]
sorry for getting out of the 
Dialogue but where did you learned coding?

**Comment by LegitSoulja** [comment]
@seifgaming from childhood, to my adult life I learned on my own as I was interested in it, even electronics.

**Comment by seifgaming** [comment]
where not when XD

**Comment by LegitSoulja** [comment]
@seifgaming um. Well. as said in my childhood years, I had/used a floppy disc. I went from home to school getting resources from the internet.. I had internet but was never able to use it. Plus it was slow dial up. This was way back 1990's. It was rough trying to learn. 

I mostly did C. Because I had Windows and the tools, and an IDE. Did alot of windows programing.

**Comment by LegitSoulja** [comment]
Since I learned C languages first,, other languages was easily understandable and I caught on quick. Thanks to object orientated programming. Just a style a group of languages use.

**Comment by LegitSoulja** [comment]
@seifgaming Anyways, I think you should get a 64 bit. I think we cover too many personal issues lol.

**Comment by LegitSoulja** [comment]
And honestly I think it would  be bad running it on a 32 bit processor.

**Comment by seifgaming** [comment]
so inspiring story i will try to learn because i have boring life i just wakeup and play clash of clans and come to login.openagar.us to see if the project finished or not so i will learn code on w3school or code acadmy

**Comment by seifgaming** [comment]
upgrading my pc to 64bit would be horrible as i have lower than 2gb 
im asusx205ta

**Comment by LegitSoulja** [comment]
@seifgaming yes everything is finished, and out as beta atm. Taking a break for OA aswell
