### ISSUE TITLE
failed to login

### ISSUE THREAD

**Issue by seifgaming** [AJS-development/OpenAgar#82]
![capture](https://user-images.githubusercontent.com/20099252/29198360-a39e651c-7e43-11e7-8e98-41c26415759d.PNG)

**Comment by LegitSoulja** [comment]
@seifgaming I'll try to look for the issue. I just pushed out our new login site.

**Comment by LegitSoulja** [comment]
Yes PHP 7 fails to do its job correctly. Fixed.

**Comment by seifgaming** [comment]
still not working

**Comment by seifgaming** [comment]
@LegitSoulja 
![capture](https://user-images.githubusercontent.com/20099252/29227326-ba0a3ea6-7ed5-11e7-8e51-28b49885e6df.PNG)

**Comment by LegitSoulja** [comment]
@seifgaming What does it say now?

**Comment by LegitSoulja** [comment]
Issue confirmed this time to be fixed.
