### ISSUE TITLE
Many people want OgarUL client...could you give me it please?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/OpenAgar#84]
Please read title...u may email me sharkfinpro@hotmail.com if you need

**Comment by Andrews54757** [comment]
Mabye, I will give it a thought. However, note that the ogarul client is awful... Bad coding right there. Kinda makes your machine turn into a jet engine

**Comment by SharkFinPro** [comment]
I know it is awful...i could possibly improve it/recode it myself tbh

But right now i just want to see how it works starting it back up using a few people on discord (i have a ton of people that want it), and if it works out well, i will recode it referencing the old client, which i cant make one without a reference bc idk fully how ogarUL is made

**Comment by LegitSoulja** [comment]
@SharkFin our client is no different from cigar's client. And many people do not want the client. 

Only you I'm afraid.

**Comment by LegitSoulja** [comment]
Also, @SharkFinPro https://github.com/AJS-development/client/tree/gh-pages

**Comment by SharkFinPro** [comment]
ok, thanks
