### ISSUE TITLE
Old  OpenAgar client source code 

### ISSUE THREAD

**Issue by bonzibuddy801** [AJS-development/OpenAgar#86]
I need the old OpenAgar client source code

![](https://cloud.githubusercontent.com/assets/13282284/25761928/9e4eb188-31aa-11e7-8049-08cc6d8ebb88.png)
 put it as a zip file please

**Comment by ZfsrGhS953** [comment]
@bonzibuddy801 What you're looking for is [Cigar](https://github.com/CigarProject/Cigar). The old ClosedAgar client is just a slightly modified version of it.

**Comment by Andrews54757** [comment]
@ZfsrGhS953 Nope, quite modified actually.

**Comment by ZfsrGhS953** [comment]
@Andrews54757 You triggered my lie detector... I see a few possibilities, from the most likely to the least:
1. You don't want to give the source code because it's not modified a lot while you say so.
2. You want to keep this "open" project closed source, to "prevent" hacking.
3. You have a cryptocurrency miner/canvas fingerprint in your code.
4. You were monkeying around with obfuscation so much that you overwrote the original file by mistake.

**Comment by Andrews54757** [comment]
@ZfsrGhS953 Nope, really, I trashed the file because I clean out my desktop every month.

<img width="1280" alt="screen shot 2017-11-04 at 5 32 15 pm" src="https://user-images.githubusercontent.com/13282284/32409651-22f659d4-c186-11e7-9949-1874bfb8f8f9.png">

**Comment by Andrews54757** [comment]
@ZfsrGhS953 No, I really trashed the file.

**Comment by ZfsrGhS953** [comment]
@Andrews54757 You trashed the file? What a genial move, now you don't even have proof to back up your arguments!
But this sentence caught my attention even more:
```I created my JS obfuscater perfectly, in one try.```
Seriously? You just wrote some code and it worked flawlessly on the first try, without debugging? Congratulations, you may be one of the smartest people on the planet. (minus the "obfuscat**e**r" spelling)
Looking at one of the obfuscated files, it seems that you just use [this](https://github.com/javascript-obfuscator/javascript-obfuscator) obfuscator, that you modified "a lot".

**Comment by Andrews54757** [comment]
@ZfsrGhS953 No shame in using their code. Of course I did! What a waste of time if I didnt.

**Comment by ZfsrGhS953** [comment]
@Andrews54757 You didn't understand me at all. I'm not saying that forking open-source projects is bad, it's claiming them as yours that is.

**Comment by Andrews54757** [comment]
@ZfsrGhS953 I never claimed that. And if you dont respect me, please leave.
