### ISSUE TITLE
Virus ?

### ISSUE THREAD

**Issue by GhostShot3** [AJS-development/OpenAgar#88]
Sorry for the question, but I have already seen a comment from another repository saying "this is a virus, if someone has this on the computer delete it immediately!" something like that, I'm afraid to test it, be honest is this virus / trojan something like or can I test normal?

**Comment by Revilum** [comment]
It's not a virus beleve me

**Comment by Andrews54757** [comment]
@GhostShot3 What? Why would this be a virus. The code is open for anyone to see. Except for the client, which we are thinking of releasing...

Nodejs is not a good platform for virus making...

It would be more effective to use a bash program.
