### ISSUE TITLE
Id Like to talk

### ISSUE THREAD

**Issue by sethdm02** [AJS-development/OpenAgar#89]
Could you guys help me with old ogar unlimited client saying cannot get / when using web client page ik this has nothing to do with this project

**Comment by SharkFinPro** [comment]
ogarUL Is gone
if you want to play, message me on discord @ 
SharkFin#0936

**Comment by sethdm02** [comment]
no i have it i just need the client ?

**Comment by SharkFinPro** [comment]
@sethdm02 
ajs-development.github.io/client/oldindex.html

**Comment by Andrews54757** [comment]
@sethdm02 https://github.com/AJS-development/client/tree/gh-pages

**Comment by sethdm02** [comment]
Yeah I tried that sadly it does. Not connect too my server
