### ISSUE TITLE
Invalid key

### ISSUE THREAD

**Issue by SevenSlayy** [AJS-development/OpenAgar#9]
I did read the other issues, and i still cant get it working.
Same invalid key error

**Comment by LegitSoulja** [comment]
Did you read on how to get the key?

**Comment by SevenSlayy** [comment]
Yes!

**Comment by SevenSlayy** [comment]
R2rAV71UlIyPZBJS0Orx

**Comment by Andrews54757** [comment]
190599824774

**Comment by Andrews54757** [comment]
@LegitSoulja I am also thinking of having OpenAgar available to the general public. I am thinking of putting a form on the forums where people can get keys. But in order to do so, they must have a account. But that is later, when this project is finished.

**Comment by SevenSlayy** [comment]
@LegitSoulja @Andrews54757 can i be like whitelisted, i wanna test this

**Comment by LegitSoulja** [comment]
@Andrews54757 I have already told you this,

But I've suggested to let beta testers generate them, but we don't want them to generate it for others.

**Comment by LegitSoulja** [comment]
We need to setup something as this for example,

User download OpenOgar, and provide there forum information.

From there, there id is updated on there account, in which they can obtain the key.

**Comment by SevenSlayy** [comment]
ye

**Comment by Andrews54757** [comment]
Providing forum information on the program itself is a bad idea due to security issues

**Comment by SevenSlayy** [comment]
So... am i gonna get to play with this or do i have to wait for the public release?

**Comment by LegitSoulja** [comment]
@Andrews54757 well let's give a key too all forum users, and that key has to be provided to OpenOgar,

Which will then update a seperate database with that server ID prior to that forum key.

User can them redeem that key.

**Comment by LegitSoulja** [comment]
Redeem there key, to get the real key*

**Comment by SevenSlayy** [comment]
Ok, so i tried it. and its ok, but very limited.

**Comment by Andrews54757** [comment]
Use the essential command plugin @SevenSlayy

**Comment by SevenSlayy** [comment]
@Andrews54757 How? i tried /OAPlugins, and nothing.

**Comment by Andrews54757** [comment]
forum.ogarul.io in resources (you must be logged in)

**Comment by SevenSlayy** [comment]
@Andrews54757 now the client says that my server cant be verified

**Comment by SevenSlayy** [comment]
@Andrews54757 it says my server is a mock server now

**Comment by Andrews54757** [comment]
I know, I am updating the client
