### ISSUE TITLE
Openagar!

### ISSUE THREAD

**Issue by Faris90** [AJS-development/OpenAgar#91]
Please Bring back OpenAgar

**Comment by SharkFinPro** [comment]
oh my...

**Comment by segg21** [comment]
@Faris90 Simple reasons as to [this](https://github.com/AJS-development/OpenAgar/issues/91) is why [OpenAgar](https://github.com/AJS-development/OpenAgar/) is closed. You're welcome. As of for you and others with no respect, and lack of home training.
