### ISSUE TITLE
Please bring back OpenAgar

### ISSUE THREAD

**Issue by Faris90** [AJS-development/OpenAgar#97]
I may have been a brute, but I loved OpenAgar, what do you say can you please bring it back?
Please don't give up on OpenAgar It is one of my favorite agar servers.
So, What do you say? bring it back or not ?

**Comment by Cabotrez** [comment]
😉

**Comment by SharkFinPro** [comment]
This project has been closed. It will not be opened back up due to a few people likeing the project, it is a big waste of time for developers that do not get paid to make it and do not have any interest in continuing making games spun off of agar.io.

**Comment by Faris90** [comment]
Welp can you at least give me the client source code?

**Comment by Faris90** [comment]
please
